import SharpWasserstein.PrescribedSwitchMarginalSourceAction
import SharpWasserstein.PrescribedSwitchMarginalSource
import SharpWasserstein.PrescribedSwitchMarginalSourceContinuity
#print axioms SharpWasserstein.PropagatedSourceEquation.Brownian.action_configuration_pairing
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedSourcePairing_eq_action
#print axioms SharpWasserstein.SwitchSourceDerivative.canonical_pairing_measure_congr
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedSourcePairing_eq_canonical_pairing
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedMarginalSource
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedMarginalSource_eq
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedMarginalSource_pairing
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedMarginalCurve
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedMarginalCurve_continuous
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedMarginalCurve_coe
#print axioms SharpWasserstein.SwitchSourceDerivative.marginal_configuration_test_bounds
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedMarginalSource_clamped_pairing
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedMarginalSource_continuous
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedMarginalCurve_integral
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedMarginalCurve_sub_eq_integral
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribed_marginal_compactDistributionContinuity
