import SharpWasserstein.PrescribedDecoupledTransport
import SharpWasserstein.WassersteinEndpointConstants
import SharpWasserstein.PrescribedSwitchEndpoint

#print axioms SharpWasserstein.PrescribedDecoupledTransport.coefficient
#print axioms SharpWasserstein.PrescribedDecoupledTransport.coefficient_nonneg
#print axioms SharpWasserstein.PrescribedDecoupledTransport.initial_le_coefficient
#print axioms SharpWasserstein.PrescribedDecoupledTransport.marginal_wassersteinSq_le
#print axioms SharpWasserstein.PrescribedDecoupledTransport.marginal_profile_uniform
#print axioms SharpWasserstein.WassersteinEndpoint.wassersteinSq_zero_particles
#print axioms SharpWasserstein.WassersteinEndpoint.initialHierarchy_allLevels
#print axioms SharpWasserstein.WassersteinEndpoint.sourceHorizonConstant_mono
#print axioms SharpWasserstein.WassersteinEndpoint.propagationConstant_mono
#print axioms SharpWasserstein.WassersteinEndpoint.switchLengthCoefficient_mono
#print axioms SharpWasserstein.WassersteinEndpoint.coefficient
#print axioms SharpWasserstein.WassersteinEndpoint.coefficient_nonneg
#print axioms SharpWasserstein.WassersteinEndpoint.transport_triangle_bound
#print axioms SharpWasserstein.WassersteinEndpoint.switch_zero_eq_supplied
#print axioms SharpWasserstein.WassersteinEndpoint.bound_of_switch_length
#print axioms SharpWasserstein.WassersteinEndpoint.bound_of_local_switch_length
#print axioms SharpWasserstein.WassersteinEndpoint.propagatedHierarchy_of_switch_lengths
