import SharpWasserstein.SwitchSourceDerivativePathwise
import SharpWasserstein.SwitchSourceDerivativeShortTime
import SharpWasserstein.SwitchSourceDerivativeRestart
import SharpWasserstein.SwitchSourceDerivativeJacobian
import SharpWasserstein.SwitchSourceDerivativeMovingTest
import SharpWasserstein.SwitchSourceDerivativeMovingExpectation
import SharpWasserstein.SwitchSourceDerivativeRemainingTest
import SharpWasserstein.SwitchSourceDerivativeLaw
import SharpWasserstein.SwitchSourceDerivativeRight
import SharpWasserstein.SwitchSourceDerivativeEquation
import SharpWasserstein.SwitchSourceDerivativeParticle
import SharpWasserstein.SwitchSourceDerivativePrescribed
import SharpWasserstein.SwitchSourceDerivativeFlux

#print axioms SharpWasserstein.SwitchSourceDerivative.strict_test_difference_hasDerivWithinAt
#print axioms SharpWasserstein.SwitchSourceDerivative.trajectory_difference_hasDerivWithinAt
#print axioms SharpWasserstein.SwitchSourceDerivative.trajectory_test_difference_hasDerivWithinAt_zero
#print axioms SharpWasserstein.SwitchSourceDerivative.trajectory_difference_norm_le
#print axioms SharpWasserstein.SwitchSourceDerivative.trajectory_test_difference_norm_le
#print axioms SharpWasserstein.SwitchSourceDerivative.flowTestDifference
#print axioms SharpWasserstein.SwitchSourceDerivative.flowTestDifference_zero
#print axioms SharpWasserstein.SwitchSourceDerivative.flowTestDifference_continuous
#print axioms SharpWasserstein.SwitchSourceDerivative.flowTestDifference_norm_le
#print axioms SharpWasserstein.SwitchSourceDerivative.flowTestDifference_hasDerivWithinAt_zero
#print axioms SharpWasserstein.SwitchSourceDerivative.integral_flowTestDifference_hasDerivWithinAt_zero
#print axioms SharpWasserstein.SwitchSourceDerivative.shiftedDrift
#print axioms SharpWasserstein.SwitchSourceDerivative.shiftedDrift_continuous
#print axioms SharpWasserstein.SwitchSourceDerivative.trajectory_shift
#print axioms SharpWasserstein.SwitchSourceDerivative.flow_add_shift
#print axioms SharpWasserstein.SwitchSourceDerivative.brownianLaw_add_shift
#print axioms SharpWasserstein.SwitchSourceDerivative.brownianGlobalLaw_add_shift
#print axioms SharpWasserstein.SwitchSourceDerivative.flow_fderiv_joint_continuous
#print axioms SharpWasserstein.SwitchSourceDerivative.expectation_fderiv_joint_continuous
#print axioms SharpWasserstein.SwitchSourceDerivative.test_sub_eq_integral_fderiv
#print axioms SharpWasserstein.SwitchSourceDerivative.trajectory_moving_test_difference_hasDerivWithinAt_zero
#print axioms SharpWasserstein.SwitchSourceDerivative.integral_moving_flowTestDifference_hasDerivWithinAt_zero
#print axioms SharpWasserstein.SwitchSourceDerivative.remainingTest
#print axioms SharpWasserstein.SwitchSourceDerivative.remainingTest_contDiff_one
#print axioms SharpWasserstein.SwitchSourceDerivative.remainingTest_norm_le
#print axioms SharpWasserstein.SwitchSourceDerivative.remainingTest_continuous
#print axioms SharpWasserstein.SwitchSourceDerivative.remainingTest_fderiv_joint_continuous
#print axioms SharpWasserstein.SwitchSourceDerivative.remainingTest_fderiv_norm_le
#print axioms SharpWasserstein.SwitchSourceDerivative.remainingTest_eq_transition
#print axioms SharpWasserstein.SwitchSourceDerivative.integral_remainingTest_eq
#print axioms SharpWasserstein.SwitchSourceDerivative.switchLaw
#print axioms SharpWasserstein.SwitchSourceDerivative.switch_integral_increment_eq
#print axioms SharpWasserstein.SwitchSourceDerivative.sourcePairing
#print axioms SharpWasserstein.SwitchSourceDerivative.switch_increment_hasDerivWithinAt_zero
#print axioms SharpWasserstein.SwitchSourceDerivative.switch_integral_hasDerivWithinAt
#print axioms SharpWasserstein.SwitchSourceDerivative.switch_integral_hasDerivWithinAt_right
#print axioms SharpWasserstein.SwitchSourceDerivative.sourcePairing_continuousOn
#print axioms SharpWasserstein.SwitchSourceDerivative.switch_integral_continuousOn
#print axioms SharpWasserstein.SwitchSourceDerivative.switch_integral_sub_eq_integral
#print axioms SharpWasserstein.SwitchSourceDerivative.switch_integral_hasDerivAt
#print axioms SharpWasserstein.SwitchSourceDerivative.particleSourcePairing
#print axioms SharpWasserstein.SwitchSourceDerivative.particle_switchLaw_eq
#print axioms SharpWasserstein.SwitchSourceDerivative.particle_switch_hasDerivAt
#print axioms SharpWasserstein.SwitchSourceDerivative.particle_switch_sub_eq_integral
#print axioms SharpWasserstein.SwitchSourceDerivative.particleRemainingTest
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedSourcePairing
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedSourcePairing_eq_current
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedSourcePairing_eq_generator_difference
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribed_switch_hasDerivAt
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribed_switch_sub_eq_integral
#print axioms SharpWasserstein.SwitchSourceDerivative.configuration_compact_test_bounds
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribed_switch_compact_hasDerivAt
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribed_switch_compact_sub_eq_integral
#print axioms SharpWasserstein.SwitchSourceDerivative.driftDifference_memLp
#print axioms SharpWasserstein.SwitchSourceDerivative.switch_flux_pairing_integrable
#print axioms SharpWasserstein.SwitchSourceDerivative.sourcePairing_eq_integral_JV
