import SharpWasserstein.VolterraHierarchy

#print axioms SharpWasserstein.VolterraHierarchy.quadraticProfile_continuous
#print axioms SharpWasserstein.VolterraHierarchy.quadraticProfile_kernel_identity
#print axioms SharpWasserstein.VolterraHierarchy.quadraticProfile_step_nonneg
#print axioms SharpWasserstein.VolterraHierarchy.quadraticProfile_rate_supersolution
#print axioms SharpWasserstein.VolterraHierarchy.quadraticProfile_volterra_supersolution
#print axioms SharpWasserstein.VolterraHierarchy.quadraticProfile_volterra_boundary
#print axioms SharpWasserstein.VolterraHierarchy.finite_quadratic_bound_variable_rate
#print axioms SharpWasserstein.VolterraHierarchy.finite_quadratic_bound
