import SharpWasserstein.RoughEulerianTimeActionMoments
import SharpWasserstein.RoughEulerianTimeActionCurve
import SharpWasserstein.RoughEulerianTimeActionCurveEnergy

#print axioms SharpWasserstein.RoughEulerianSmoothing.averagedKernel_norm_le
#print axioms SharpWasserstein.RoughEulerianSmoothing.density_eq_zero_of_norm_gt
#print axioms SharpWasserstein.RoughEulerianSmoothing.regularizedLaw_quadratic_le
#print axioms SharpWasserstein.RoughEulerianSmoothing.spaceTimeRegularizedLaw_quadratic
#print axioms SharpWasserstein.RoughEulerianSmoothing.spaceTimeRegularizedLaw_integral_test_continuous
#print axioms SharpWasserstein.RoughEulerianSmoothing.averagingTime
#print axioms SharpWasserstein.RoughEulerianSmoothing.averagingTime_mem
#print axioms SharpWasserstein.RoughEulerianSmoothing.averagingTime_continuous
#print axioms SharpWasserstein.RoughEulerianSmoothing.averagingTime_eq
#print axioms SharpWasserstein.RoughEulerianSmoothing.spaceTimeProbabilityCurve
#print axioms SharpWasserstein.RoughEulerianSmoothing.spaceTimeProbabilityCurve_coe
#print axioms SharpWasserstein.RoughEulerianSmoothing.spaceTimeProbabilityCurve_quadratic
#print axioms SharpWasserstein.RoughEulerianSmoothing.spaceTimeProbabilityCurve_continuous
#print axioms SharpWasserstein.RoughEulerianSmoothing.spaceTimeProbabilityCurve_action
#print axioms SharpWasserstein.RoughEulerianSmoothing.compProd_norm_le
#print axioms SharpWasserstein.RoughEulerianSmoothing.hasSecondMoment_configuration_of_quadratic
