import SharpWasserstein.RoughEulerianTransportRegular
import SharpWasserstein.RoughEulerianTransportLimit
#print axioms SharpWasserstein.RoughEulerianTransport.integral_sqrt_sq_le_time_mul
#print axioms SharpWasserstein.RoughEulerianTransport.regular_wassersteinSq_le_finiteAction
#print axioms SharpWasserstein.RoughEulerianTransport.quadraticLaw_tendsto_of_wassersteinSq
#print axioms SharpWasserstein.RoughEulerianTransport.wassersteinSq_tendsto_of_endpoints
#print axioms SharpWasserstein.RoughEulerianTransport.wassersteinSq_le_of_regularized_endpoints
#print axioms SharpWasserstein.RoughEulerianTransport.wassersteinSq_le_of_regularized_action_limit
