import SharpWasserstein.RoughEulerianTransportTimeMixture
import SharpWasserstein.RoughEulerianTransportTimeEndpoint
import SharpWasserstein.RoughCommonLabelLift
import SharpWasserstein.RoughCommonLabelTimeEndpoint
#print axioms SharpWasserstein.RoughEulerianTransport.timeSampling
#print axioms SharpWasserstein.RoughEulerianTransport.timeSampling_probability
#print axioms SharpWasserstein.RoughEulerianTransport.timeSampling_support
#print axioms SharpWasserstein.RoughEulerianTransport.timeSampling_lintegral_tendsto_zero
#print axioms SharpWasserstein.RoughEulerianTransport.averagedKernel_eq_commonLabel
#print axioms SharpWasserstein.RoughEulerianTransport.averagedKernel_configuration_eq_commonLabel
#print axioms SharpWasserstein.RoughEulerianTransport.averagedKernel_wassersteinSq_le_commonLabel
#print axioms SharpWasserstein.RoughEulerianTransport.averagedKernel_wassersteinSq_tendsto_commonLabel
#print axioms SharpWasserstein.RoughEulerianTransport.wassersteinSq_tendsto_zero_triangle
#print axioms SharpWasserstein.RoughEulerianTransport.regularizedLaw_moving_wassersteinSq_tendsto
#print axioms SharpWasserstein.RoughEulerianTransport.spaceTimeRegularizedLaw_wassersteinSq_tendsto_commonLabel
#print axioms SharpWasserstein.RoughEulerianTransport.CommonLabelLift
#print axioms SharpWasserstein.RoughEulerianTransport.CommonLabelLift.translate
#print axioms SharpWasserstein.RoughEulerianTransport.CommonLabelLift.law_euclidean
#print axioms SharpWasserstein.RoughEulerianTransport.CommonLabelLift.configurationCompression_pair_cost_le
#print axioms SharpWasserstein.RoughEulerianTransport.CommonLabelLift.compress
#print axioms SharpWasserstein.RoughEulerianTransport.CommonLabelLift.averagedKernel_wassersteinSq_tendsto
#print axioms SharpWasserstein.RoughEulerianTransport.CommonLabelLift.spaceTimeRegularizedLaw_wassersteinSq_tendsto
