/-
Copyright (c) 2026 Raphael Coelho. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Raphael Coelho
-/
module

public import MathFin.Foundations.ItoIntegralL2

/-! # Countable generation of the Brownian σ-algebra

The natural filtration `𝓕ᴮ_T = σ(B_s : s ≤ T)` (`ItoIntegralL2.natFiltration`) is an
*uncountable* supremum — one `comap (B s)` for every `s` in `[0,T]`. Nothing in that
definition says the σ-algebra is generated by countably many coordinates, and for a
process with arbitrary paths it is not.

**Path continuity is what changes that, and it is the entire content of this file.**
A continuous path is determined by its values on a dense set, so `B_s` is the
pointwise limit of `B_q` along dyadic grid points `q → s`, and a pointwise limit of
measurable functions is measurable (`measurable_of_tendsto_metrizable`). The
uncountable supremum therefore collapses onto the countable chain of *finite*
cylinder σ-algebras `σ(B_q : q ∈ dyadicGrid T n)`:

`⨆ₙ σ(B_q : q ∈ {k·T/2ⁿ : k ≤ 2ⁿ}) = 𝓕ᴮ_T`.

The two inclusions are wildly asymmetric. `≤` is bookkeeping: every grid point lies
in `[0,T]`. `≥` is the theorem, and `hBcont` is used there and nowhere else — drop it
and the statement is false.

The nearest grid point at or below `s` is `⌊(s/T)·2ⁿ⌋·T/2ⁿ`, and its convergence to
`s` is Mathlib's `tendsto_nat_floor_mul_div_atTop` read along `x = 2ⁿ`. The
degenerate horizon `T = 0` needs no separate branch: `s/T·T = s` survives it, because
`s ≤ T = 0` forces `s = 0` and Lean's `x/0 = 0`.

## Downstream

`cylinderFiltration` bundles the cylinder σ-algebras as an `ℕ`-filtration, which is
the shape Lévy's upward theorem wants (`MeasureTheory.Integrable.tendsto_ae_condExp`
and its `eLpNorm` companion): conditional expectations along a filtration converge to
the conditional expectation on the limit σ-algebra. That is how the
martingale-representation argument pushes a `𝓕ᴮ_T`-measurable `L²` variable onto the
countably many coordinates the Wiener-exponential totality argument can see.

## Result

* `dyadicGrid`, `dyadicGrid_le`, `dyadicGrid_mono` — the grid `{k·T/2ⁿ : k ≤ 2ⁿ}`, the fact
  that it sits in `[0,T]`, and the nesting that makes `cylinderFiltration` monotone.
* `cylinderSigma` — the σ-algebra generated by the process at the `n`-th grid.
* `cylinderFiltration` — those σ-algebras bundled as an `ℕ`-filtration.
* `iSup_cylinderSigma_eq_natFiltration` — **countable generation**: for a process with
  continuous paths the uncountable supremum `σ(B_s : s ≤ T)` is `⨆ₙ cylinderSigma B T n`.
* `iSup_cylinderFiltration_eq_natFiltration` — the same, in the filtration vocabulary Lévy's
  upward theorem consumes.
-/

@[expose] public section

namespace MathFin

open MeasureTheory Filter
open scoped NNReal Topology

variable {Ω : Type*} [mΩ : MeasurableSpace Ω] {B : ℝ≥0 → Ω → ℝ}

/-- The dyadic grid `{k·T/2^n : k ≤ 2^n}` on `[0,T]`. -/
noncomputable def dyadicGrid (T : ℝ≥0) (n : ℕ) : Finset ℝ≥0 :=
  (Finset.range (2 ^ n + 1)).image fun k : ℕ ↦ (k : ℝ≥0) * T / (2 ^ n)

/-- Every dyadic grid point lies in `[0,T]`: `k ≤ 2ⁿ` gives `k·T/2ⁿ ≤ T`. -/
lemma dyadicGrid_le {T : ℝ≥0} {n : ℕ} {q : ℝ≥0} (hq : q ∈ dyadicGrid T n) : q ≤ T := by
  obtain ⟨k, hk, rfl⟩ := Finset.mem_image.mp hq
  have hk' : (k : ℝ≥0) ≤ 2 ^ n := by
    exact_mod_cast Nat.lt_succ_iff.mp (Finset.mem_range.mp hk)
  rw [div_le_iff₀ (by positivity : (0 : ℝ≥0) < 2 ^ n), mul_comm T]
  exact mul_le_mul_of_nonneg_right hk' zero_le

/-- The grids nest: refining `n` to `n+1` sends `k·T/2ⁿ` to `2k·T/2ⁿ⁺¹`. `Monotone`
into `Finset` is `⊆`, which is what makes `cylinderFiltration` a filtration. -/
lemma dyadicGrid_mono (T : ℝ≥0) : Monotone (dyadicGrid T) := by
  refine monotone_nat_of_le_succ fun n q hq ↦ ?_
  obtain ⟨k, hk, rfl⟩ := Finset.mem_image.mp hq
  rw [Finset.mem_range] at hk
  refine Finset.mem_image.mpr ⟨2 * k, Finset.mem_range.mpr ?_, ?_⟩
  · have h2 : 2 ^ (n + 1) = 2 * 2 ^ n := by ring
    omega
  · push_cast
    rw [show ((2 : ℝ≥0) ^ (n + 1)) = 2 * 2 ^ n by ring, mul_assoc,
      mul_div_mul_left _ _ two_ne_zero]

/-- The σ-algebra generated by the process at the `n`-th dyadic grid. -/
@[reducible] noncomputable def cylinderSigma (B : ℝ≥0 → Ω → ℝ) (T : ℝ≥0) (n : ℕ) :
    MeasurableSpace Ω :=
  ⨆ q ∈ dyadicGrid T n, MeasurableSpace.comap (B q) inferInstance

/-- The cylinder σ-algebras bundled as an `ℕ`-filtration: the shape
`Integrable.tendsto_ae_condExp` / `Integrable.tendsto_eLpNorm_condExp` demand. -/
noncomputable def cylinderFiltration (B : ℝ≥0 → Ω → ℝ) (T : ℝ≥0)
    (hBmeas : ∀ t, Measurable (B t)) : Filtration ℕ mΩ where
  seq n := cylinderSigma B T n
  mono' _ _ h := biSup_mono fun _ hq ↦ dyadicGrid_mono T h hq
  le' _ := iSup₂_le fun q _ ↦ (hBmeas q).comap_le

/-- **The Brownian σ-algebra is countably generated by dyadic cylinders.** For a
process with continuous paths the uncountable supremum `σ(B_s : s ≤ T)` collapses onto
the countable chain `⨆ₙ σ(B_q : q ∈ dyadicGrid T n)`. `≤` only needs the grid to sit in
`[0,T]`; `≥` is where continuity is used, and it is used nowhere else. -/
theorem iSup_cylinderSigma_eq_natFiltration (hBmeas : ∀ t, Measurable (B t))
    (hBcont : ∀ ω, Continuous fun s : ℝ≥0 ↦ B s ω) (T : ℝ≥0) :
    (⨆ n : ℕ, cylinderSigma B T n)
      = (ItoIntegralL2.natFiltration (mΩ := mΩ) hBmeas) T := by
  have hnat : (ItoIntegralL2.natFiltration (mΩ := mΩ) hBmeas) T
      = ⨆ r : ℝ≥0, ⨆ _ : r ≤ T, MeasurableSpace.comap (B r) inferInstance := rfl
  rw [hnat]
  refine le_antisymm
    (iSup_le fun n ↦ iSup₂_le fun r hr ↦
      le_iSup₂ (f := fun u (_ : u ≤ T) ↦ MeasurableSpace.comap (B u) inferInstance) r
        (dyadicGrid_le hr))
    (iSup₂_le fun s hs ↦ ?_)
  -- The dyadic approximants of `s`: the nearest grid point at or below it.
  obtain ⟨q, hqmem, hq⟩ : ∃ q : ℕ → ℝ≥0,
      (∀ n, q n ∈ dyadicGrid T n) ∧ Tendsto q atTop (𝓝 s) := by
    have ha0 : (0 : ℝ) ≤ (s : ℝ) / (T : ℝ) := div_nonneg s.coe_nonneg T.coe_nonneg
    have ha1 : (s : ℝ) / (T : ℝ) ≤ 1 := by
      rcases eq_or_lt_of_le T.coe_nonneg with hT | hT
      · simp [← hT]
      · exact (div_le_one hT).mpr (NNReal.coe_le_coe.mpr hs)
    refine ⟨fun n ↦ (⌊(s : ℝ) / (T : ℝ) * 2 ^ n⌋₊ : ℝ≥0) * T / 2 ^ n, fun n ↦ ?_, ?_⟩
    · refine Finset.mem_image.mpr ⟨⌊(s : ℝ) / (T : ℝ) * 2 ^ n⌋₊,
        Finset.mem_range.mpr (Nat.lt_succ_of_le (Nat.floor_le_of_le ?_)), rfl⟩
      push_cast
      exact mul_le_of_le_one_left (by positivity) ha1
    · have haT : (s : ℝ) / (T : ℝ) * (T : ℝ) = (s : ℝ) := by
        rcases eq_or_ne (T : ℝ) 0 with hT | hT
        · have hs0 : (s : ℝ) = 0 := by
            have h := NNReal.coe_le_coe.mpr hs
            rw [hT] at h
            exact le_antisymm h s.coe_nonneg
          rw [hT, hs0]
          simp
        · exact div_mul_cancel₀ _ hT
      have h1 := ((tendsto_nat_floor_mul_div_atTop ha0).comp
        (tendsto_pow_atTop_atTop_of_one_lt (by norm_num : (1 : ℝ) < 2))).mul_const (T : ℝ)
      rw [haT] at h1
      rw [← NNReal.tendsto_coe]
      refine Tendsto.congr (fun n ↦ ?_) h1
      simp only [Function.comp_apply]
      push_cast
      ring
  -- `B s` is a pointwise limit of `⨆ₙ cylinderSigma`-measurable functions.
  have hgrid (n : ℕ) : Measurable[⨆ m : ℕ, cylinderSigma B T m] (B (q n)) :=
    Measurable.of_comap_le <|
      (le_iSup₂ (f := fun r (_ : r ∈ dyadicGrid T n) ↦
        MeasurableSpace.comap (B r) inferInstance) (q n) (hqmem n)).trans
          (le_iSup (fun m : ℕ ↦ cylinderSigma B T m) n)
  have key : Measurable[⨆ n : ℕ, cylinderSigma B T n] (B s) :=
    @measurable_of_tendsto_metrizable Ω ℝ (⨆ n : ℕ, cylinderSigma B T n) _ _ _ _
      (fun n ↦ B (q n)) (B s) hgrid
      (tendsto_pi_nhds.mpr fun ω ↦ ((hBcont ω).tendsto s).comp hq)
  exact key.comap_le

/-- The filtration-bundled restatement, the form Lévy's upward theorem consumes:
`cylinderFiltration` is a filtration whose limit σ-algebra is `𝓕ᴮ_T`. -/
theorem iSup_cylinderFiltration_eq_natFiltration (hBmeas : ∀ t, Measurable (B t))
    (hBcont : ∀ ω, Continuous fun s : ℝ≥0 ↦ B s ω) (T : ℝ≥0) :
    (⨆ n : ℕ, (cylinderFiltration B T hBmeas) n)
      = (ItoIntegralL2.natFiltration (mΩ := mΩ) hBmeas) T :=
  iSup_cylinderSigma_eq_natFiltration hBmeas hBcont T

end MathFin
