/-
Copyright (c) 2026 Raphael Coelho. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Raphael Coelho
-/
module

public import Mathlib
public import BrownianMotion.Gaussian.BrownianMotion

/-!
# Brownian Markov property at the σ-algebra level

Degenne's `BrownianMotion` package proves the weak Markov property in the
function-valued form: `IsPreBrownianReal.indepFun_shift` states that the shifted
increment map `ω ↦ (X (t₀ + t) ω − X t₀ ω)_t` is independent (as a random
variable valued in `ℝ≥0 → ℝ`) of the past evaluation map
`ω ↦ (X t ω)_{t ≤ t₀}`, and `IsPreBrownianReal.shift` states the shifted process
is again a pre-Brownian motion.

The textbook statement (Saporito, Theorem 5.1.4) is the σ-algebra form: the
post-`t₀` increment process is independent of the **natural filtration**
`𝓕ᵉ_{t₀} = σ(X_u : u ≤ t₀)`. This file closes that gap: by
`Filtration.natural_eq_comap`, the natural σ-algebra at `t₀` *is* the comap of
the past evaluation map, so the function-valued independence upgrades to

  `Indep σ(shifted increments) (Filtration.natural X _ t₀) P`,

which together with `IsPreBrownianReal.shift` is the full textbook package: after
`t₀`, Brownian motion **restarts afresh, independently of its entire past**.

## Main results

* `shift_indep_natural` — σ(increments after `t₀`) is independent of the
  natural filtration at `t₀`.
* `brownian_markov_property` — the textbook package: the shifted increment
  process is a pre-Brownian motion *and* independent of `𝓕ᵉ_{t₀}`.
-/

@[expose] public section

namespace MathFin

open MeasureTheory ProbabilityTheory
open scoped NNReal ENNReal

variable {Ω : Type*} {mΩ : MeasurableSpace Ω} {P : Measure Ω}
  {X : ℝ≥0 → Ω → ℝ}

/-- **σ-algebra form of the weak Markov property.** The σ-algebra generated by
the shifted increment map `ω ↦ (X (t₀ + t) ω − X t₀ ω)_t` is independent of
the natural filtration `σ(X_u : u ≤ t₀)`. Upgrade of Degenne's
`IsPreBrownianReal.indepFun_shift` via `Filtration.natural_eq_comap`. -/
theorem shift_indep_natural (h : IsPreBrownianReal X P)
    (hX : ∀ t, Measurable (X t)) (t₀ : ℝ≥0) :
    Indep
      (MeasurableSpace.comap (fun ω (t : ℝ≥0) ↦ X (t₀ + t) ω - X t₀ ω) inferInstance)
      (Filtration.natural X (fun t ↦ (hX t).stronglyMeasurable) t₀) P := by
  rw [Filtration.natural_eq_comap]
  exact (IndepFun_iff_Indep _ _ _).1 (h.indepFun_shift t₀)

/-- **Theorem 5.1.4 (Brownian Markov property).** For a pre-Brownian motion
`X` and any `t₀ ≥ 0`, the post-`t₀` increment process
`t ↦ X (t₀ + t) − X t₀` is itself a pre-Brownian motion, and it is
independent of the natural filtration `𝓕ᵉ_{t₀} = σ(X_u : u ≤ t₀)` — the
σ-algebra of the *entire* past, not merely finitely many past evaluations. -/
theorem brownian_markov_property (h : IsPreBrownianReal X P)
    (hX : ∀ t, Measurable (X t)) (t₀ : ℝ≥0) :
    IsPreBrownianReal (fun t ω ↦ X (t₀ + t) ω - X t₀ ω) P ∧
    Indep
      (MeasurableSpace.comap (fun ω (t : ℝ≥0) ↦ X (t₀ + t) ω - X t₀ ω) inferInstance)
      (Filtration.natural X (fun t ↦ (hX t).stronglyMeasurable) t₀) P :=
  ⟨h.shift t₀, shift_indep_natural h hX t₀⟩

end MathFin
