/-
Copyright (c) 2026 Raphael Coelho. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Raphael Coelho
-/
module

public import MathFin.Foundations.ItoIntegralProcessContinuousModification

/-!
# The general-integrand Itô integral as a continuous local martingale

The continuous modification (`itoContinuousMod`) is a martingale that is
continuous only *almost surely* — its `limUnder` paths are junk off the
convergence set. Degenne's `Martingale.IsLocalMartingale` needs paths càdlàg for
**every** `ω`, which forces an everywhere-continuous representative; but the
modification on a null set can only be repaired while staying adapted if the
filtration carries the null sets. This file builds the **null-augmented
filtration** `𝓕 ⊔ 𝓝` (`𝓝` = the σ-algebra of `μ`-null measurable sets) — the
**completeness** half of the "usual conditions" (right-continuity, the other
half, is neither added nor needed here) — together with the
cond-expectation-invariance under it. These are the measure-theoretic core of the
everywhere-continuous local-martingale upgrade in
`exists_continuous_localMartingale_modification`.
-/

@[expose] public section

open MeasureTheory ProbabilityTheory Filter Topology
open scoped NNReal ENNReal

namespace MathFin
namespace ItoLocalMartingale

variable {Ω : Type*} {m0 : MeasurableSpace Ω} {μ : Measure Ω}

/-- The σ-algebra generated by the `μ`-null **measurable** sets (so it stays
`≤ m0`). It contains every measurable null set; augmenting a filtration by it
supplies the **completeness** (null-set augmentation) needed to repair an
a.e.-continuous modification into an everywhere-continuous adapted process. -/
@[reducible] def nullsAlg (m0 : MeasurableSpace Ω) (μ : Measure Ω) : MeasurableSpace Ω :=
  MeasurableSpace.generateFrom {s | MeasurableSet[m0] s ∧ μ s = 0}

lemma nullsAlg_le : nullsAlg m0 μ ≤ m0 :=
  MeasurableSpace.generateFrom_le fun _ hs ↦ hs.1

/-- **The measure-theoretic crux.** Every set measurable for the null-augmented
σ-algebra `m₁ ⊔ 𝓝` is `μ`-a.e. equal to an `m₁`-measurable set. This is exactly
membership in Mathlib's `eventuallyMeasurableSpace m₁ (ae μ)` — the σ-algebra of
sets `=ᵐ` an `m₁`-set — which dominates both `m₁` (`le_eventuallyMeasurableSpace`)
and the null generators of `𝓝` (each `=ᵐ ∅`), hence their supremum. -/
theorem exists_ae_eq_of_sup_nulls {m₁ : MeasurableSpace Ω}
    {s : Set Ω} (hs : MeasurableSet[m₁ ⊔ nullsAlg m0 μ] s) :
    ∃ t, MeasurableSet[m₁] t ∧ s =ᵐ[μ] t := by
  exact (sup_le le_eventuallyMeasurableSpace
    (MeasurableSpace.generateFrom_le fun _ hu ↦
      ⟨∅, m₁.measurableSet_empty, ae_eq_empty.mpr hu.2⟩) :
    m₁ ⊔ nullsAlg m0 μ ≤ eventuallyMeasurableSpace m₁ (ae μ)) s hs

/-- **Cond-expectation invariance under the null augmentation.** Conditioning on
the null-augmented σ-algebra `m₁ ⊔ 𝓝` agrees `μ`-a.e. with conditioning on `m₁`:
the extra information is only null sets, which carry no information. Proof:
`μ[f | m₁]` is `m₁`-measurable (hence `(m₁ ⊔ 𝓝)`-measurable) and satisfies the
`(m₁ ⊔ 𝓝)`-set-integral characterisation of the conditional expectation, because
every `(m₁ ⊔ 𝓝)`-set is `=ᵐ` an `m₁`-set (`exists_ae_eq_of_sup_nulls`) over which
the `m₁`-characterisation already holds. -/
theorem condExp_sup_nulls [IsFiniteMeasure μ] {m₁ : MeasurableSpace Ω} (hm₁ : m₁ ≤ m0)
    {f : Ω → ℝ} (hf : Integrable f μ) :
    μ[f | m₁ ⊔ nullsAlg m0 μ] =ᵐ[μ] μ[f | m₁] := by
  have hm : m₁ ⊔ nullsAlg m0 μ ≤ m0 := sup_le hm₁ nullsAlg_le
  haveI : SigmaFinite (μ.trim hm₁) := (isFiniteMeasure_trim hm₁).toSigmaFinite
  haveI : SigmaFinite (μ.trim hm) := (isFiniteMeasure_trim hm).toSigmaFinite
  refine (ae_eq_condExp_of_forall_setIntegral_eq hm hf
    (fun s _ _ ↦ integrable_condExp.integrableOn) (fun s hs _ ↦ ?_)
    ((stronglyMeasurable_condExp.mono le_sup_left).aestronglyMeasurable)).symm
  obtain ⟨t, htm, hst⟩ := exists_ae_eq_of_sup_nulls hs
  rw [setIntegral_congr_set hst, setIntegral_condExp hm₁ hf htm]
  exact (setIntegral_congr_set hst).symm

end ItoLocalMartingale

namespace ItoIntegralProcessLocalMartingaleGeneral

open ItoIntegralL2 ItoIntegralCLM ItoIntegralProcess ItoIntegralProcessGeneral
open ItoIntegralProcessContinuousModification ItoLocalMartingale

variable {Ω : Type*} {m0 : MeasurableSpace Ω} {μ : Measure Ω}
  [IsProbabilityMeasure μ] {B : ℝ≥0 → Ω → ℝ} (hB : IsPreBrownianReal B μ)

/-- The **null-augmented Brownian filtration** `𝓕ᴮ ⊔ 𝓝`: at each time it adjoins the
`μ`-null measurable sets to `𝓕ᴮ_t`. This supplies the **completeness** (null-set
augmentation) needed to repair the a.e.-continuous modification into an
everywhere-continuous *adapted* process; right-continuity, the other half of the
"usual conditions", is not added and not needed here. -/
noncomputable def augFiltration (hBmeas : ∀ t, Measurable (B t)) : Filtration ℝ≥0 m0 :=
  natFiltration hBmeas ⊔ Filtration.const ℝ≥0 (nullsAlg m0 μ) nullsAlg_le

omit [IsProbabilityMeasure μ] in
@[simp] lemma augFiltration_apply (hBmeas : ∀ t, Measurable (B t)) (i : ℝ≥0) :
    augFiltration (μ := μ) hBmeas i = natFiltration hBmeas i ⊔ nullsAlg m0 μ := rfl

/-- The **everywhere-defined representative**: the continuous modification clamped to
`[0,T]` via `min · T` (constant past `T`), zeroed off the good set `G`. On `G` it is the
genuine continuous path; off the `μ`-null `Gᶜ` it is `0`. -/
noncomputable def itoLocalMod (G : Set Ω) (T t : ℝ≥0) (hBmeas : ∀ s, Measurable (B s))
    (φ : Lp ℝ 2 (trimMeasure_T (μ := μ) T hBmeas)) (ω : Ω) : ℝ :=
  G.indicator (fun ω ↦ itoContinuousMod T hBmeas φ (min t T) ω) ω

/-- **The general-integrand Itô process has an everywhere-continuous local-martingale
representative.** There is a process `X : ℝ≥0 → Ω → ℝ` that (i) is a **modification** of
the `L²` Itô process on the horizon — `X t =ᵐ itoProcessCLM T t φ` for every `t ≤ T`;
(ii) has **everywhere**-continuous paths; (iii) is a genuine `IsLocalMartingale` for the
**null-augmented** Brownian filtration `augFiltration` (the martingale property holds globally
on `ℝ≥0`, the clamp `min · T` freezing it past `T`; only the modification clause (i) is
horizon-scoped); and (iv) is `StronglyMeasurable[augFiltration i]` at each `i` — the per-horizon
adaptedness, exposed explicitly so the `[0,∞)` gluing arc can consume it. This upgrades the gate
(`exists_continuous_modification_itoProcess`, an
a.e.-continuous *modification*) to Degenne's local-martingale interface, whose `∀ ω, IsCadlag`
hypothesis forces the everywhere-continuous representative: its **adaptedness** the null
augmentation supplies (the repaired good set `G ∈ 𝓝`), its **martingale property** transferring
across the augmentation via `condExp_sup_nulls`. -/
theorem exists_continuous_localMartingale_modification (T : ℝ≥0)
    (hBmeas : ∀ t, Measurable (B t)) (hBcont : ∀ ω, Continuous fun t : ℝ≥0 ↦ B t ω)
    (φ : Lp ℝ 2 (trimMeasure_T (μ := μ) T hBmeas)) :
    ∃ X : ℝ≥0 → Ω → ℝ,
      (∀ t, t ≤ T → X t =ᵐ[μ] itoProcessCLM hB T t hBmeas φ) ∧
      (∀ ω, Continuous fun t ↦ X t ω) ∧
      IsLocalMartingale X (augFiltration (μ := μ) hBmeas) μ ∧
      (∀ i, StronglyMeasurable[augFiltration (μ := μ) hBmeas i] (X i)) := by
  -- the a.e. good behaviour: pointwise convergence (∀ t ≤ T) + path continuity on [0,T]
  have hae : ∀ᵐ ω ∂μ,
      (∀ t : ℝ≥0, t ≤ T → Tendsto
        (fun n ↦ itoSimpleProcess hBmeas ((approxSeq T hBmeas φ).choose n).val t ω) atTop
        (𝓝 (itoContinuousMod T hBmeas φ t ω)))
      ∧ ContinuousOn (fun t ↦ itoContinuousMod T hBmeas φ t ω) (Set.Icc 0 T) := by
    filter_upwards [itoContinuousMod_tendsto hB T hBmeas hBcont φ,
      itoContinuousMod_continuousOn hB T hBmeas hBcont φ] with ω h1 h2 using ⟨h1, h2⟩
  -- extract a genuinely measurable, co-null, augmentation-measurable good set G = Nᶜ
  obtain ⟨N, hsubN, hNmeas, hNnull⟩ := exists_measurable_superset_of_null (ae_iff.mp hae)
  set G : Set Ω := Nᶜ with hGdef
  have hGnull : μ Gᶜ = 0 := by rw [hGdef, compl_compl]; exact hNnull
  have hGaug : MeasurableSet[nullsAlg m0 μ] G := by
    rw [hGdef]
    exact (MeasurableSpace.measurableSet_generateFrom
      (show N ∈ {s | MeasurableSet[m0] s ∧ μ s = 0} from ⟨hNmeas, hNnull⟩)).compl
  have hGgood : ∀ ω ∈ G,
      (∀ t : ℝ≥0, t ≤ T → Tendsto
        (fun n ↦ itoSimpleProcess hBmeas ((approxSeq T hBmeas φ).choose n).val t ω) atTop
        (𝓝 (itoContinuousMod T hBmeas φ t ω)))
      ∧ ContinuousOn (fun t ↦ itoContinuousMod T hBmeas φ t ω) (Set.Icc 0 T) := by
    intro ω hω
    rw [hGdef, Set.mem_compl_iff] at hω
    exact not_not.mp (fun h ↦ hω (hsubN h))
  have hGtend := fun ω hω ↦ (hGgood ω hω).1
  have hGcont := fun ω hω ↦ (hGgood ω hω).2
  -- (1) modification: X i =ᵐ itoProcessCLM T (min i T) φ
  have hmod : ∀ i : ℝ≥0, (fun ω ↦ itoLocalMod G T i hBmeas φ ω)
      =ᵐ[μ] (itoProcessCLM hB T (min i T) hBmeas φ : Ω → ℝ) := by
    intro i
    have hstep : (fun ω ↦ itoLocalMod G T i hBmeas φ ω)
        =ᵐ[μ] (fun ω ↦ itoContinuousMod T hBmeas φ (min i T) ω) := by
      have hG_ae : ∀ᵐ ω ∂μ, ω ∈ G := by rw [ae_iff]; exact hGnull
      filter_upwards [hG_ae] with ω hω
      simp only [itoLocalMod, Set.indicator_of_mem hω]
    exact hstep.trans (itoContinuousMod_modification hB T hBmeas hBcont φ (min_le_right i T))
  -- (2) the L²-process martingale identity at clamped indices min i T ≤ min j T
  have hCLMmart : ∀ {i j : ℝ≥0}, i ≤ j →
      μ[(itoProcessCLM hB T (min j T) hBmeas φ : Ω → ℝ) | natFiltration hBmeas i]
        =ᵐ[μ] (itoProcessCLM hB T (min i T) hBmeas φ : Ω → ℝ) := by
    intro i j hij
    by_cases hiT : i ≤ T
    · rw [min_eq_left hiT]
      exact itoIntegralProcessGen_isMartingale hB T hBmeas φ (le_min hij hiT)
    · have hTi : T ≤ i := (not_le.mp hiT).le
      rw [min_eq_right (hTi.trans hij), min_eq_right hTi]
      refine condExp_of_aestronglyMeasurable' ((natFiltration hBmeas).le i) ?_
        ((Lp.memLp _).integrable (by norm_num))
      obtain ⟨g, hg, hfg⟩ := itoProcessCLM_aeStronglyMeasurable hB T T hBmeas φ
      exact ⟨g, hg.mono ((natFiltration hBmeas).mono hTi), hfg⟩
  -- (3) the augmented martingale condExp identity for X
  have hmart : ∀ {i j : ℝ≥0}, i ≤ j →
      μ[(fun ω ↦ itoLocalMod G T j hBmeas φ ω) | natFiltration hBmeas i ⊔ nullsAlg m0 μ]
        =ᵐ[μ] (fun ω ↦ itoLocalMod G T i hBmeas φ ω) := by
    intro i j hij
    calc μ[(fun ω ↦ itoLocalMod G T j hBmeas φ ω) | natFiltration hBmeas i ⊔ nullsAlg m0 μ]
        =ᵐ[μ] μ[(itoProcessCLM hB T (min j T) hBmeas φ : Ω → ℝ)
            | natFiltration hBmeas i ⊔ nullsAlg m0 μ] := condExp_congr_ae (hmod j)
      _ =ᵐ[μ] μ[(itoProcessCLM hB T (min j T) hBmeas φ : Ω → ℝ) | natFiltration hBmeas i] :=
          condExp_sup_nulls ((natFiltration hBmeas).le i) ((Lp.memLp _).integrable (by norm_num))
      _ =ᵐ[μ] (itoProcessCLM hB T (min i T) hBmeas φ : Ω → ℝ) := hCLMmart hij
      _ =ᵐ[μ] (fun ω ↦ itoLocalMod G T i hBmeas φ ω) := (hmod i).symm
  -- (4) everywhere continuity of the paths
  have hcont : ∀ ω, Continuous (fun t ↦ itoLocalMod G T t hBmeas φ ω) := by
    intro ω
    by_cases hω : ω ∈ G
    · have hrw : (fun t ↦ itoLocalMod G T t hBmeas φ ω)
          = fun t ↦ itoContinuousMod T hBmeas φ (min t T) ω :=
        funext fun t ↦ by simp only [itoLocalMod, Set.indicator_of_mem hω]
      rw [hrw]
      exact (hGcont ω hω).comp_continuous (continuous_id.min continuous_const)
        (fun t ↦ ⟨zero_le, min_le_right _ _⟩)
    · have hrw : (fun t ↦ itoLocalMod G T t hBmeas φ ω) = fun _ ↦ (0 : ℝ) :=
        funext fun t ↦ by simp only [itoLocalMod, Set.indicator_of_notMem hω]
      rw [hrw]; exact continuous_const
  -- (5) adaptedness to the augmented filtration (the augmentation-measurability core)
  have hadapt : ∀ i : ℝ≥0, StronglyMeasurable[natFiltration hBmeas i ⊔ nullsAlg m0 μ]
      (fun ω ↦ itoLocalMod G T i hBmeas φ ω) := by
    intro i
    refine stronglyMeasurable_of_tendsto atTop
      (f := fun n ↦ G.indicator
        (fun ω ↦ itoSimpleProcess hBmeas ((approxSeq T hBmeas φ).choose n).val (min i T) ω))
      (fun n ↦ ?_) ?_
    · exact (((itoSimpleProcess_isMartingale hB hBmeas
          ((approxSeq T hBmeas φ).choose n).val).1 (min i T)).mono
        (((natFiltration hBmeas).mono (min_le_left i T)).trans le_sup_left)).indicator
        ((le_sup_right : nullsAlg m0 μ ≤ natFiltration hBmeas i ⊔ nullsAlg m0 μ) _ hGaug)
    · refine tendsto_pi_nhds.mpr (fun ω ↦ ?_)
      by_cases hω : ω ∈ G
      · simp only [Set.indicator_of_mem hω, itoLocalMod]
        exact hGtend ω hω (min i T) (min_le_right i T)
      · simp only [Set.indicator_of_notMem hω, itoLocalMod]
        exact tendsto_const_nhds
  -- assemble
  refine ⟨fun t ω ↦ itoLocalMod G T t hBmeas φ ω, fun t ht ↦ ?_, hcont, ?_,
    fun i ↦ by rw [augFiltration_apply]; exact hadapt i⟩
  · have h := hmod t; rwa [min_eq_left ht] at h
  · refine Martingale.IsLocalMartingale ⟨fun i ↦ ?_, fun i j hij ↦ ?_⟩
      (fun ω ↦ (hcont ω).isCadlag)
    · rw [augFiltration_apply]; exact hadapt i
    · rw [augFiltration_apply]; exact hmart hij

end ItoIntegralProcessLocalMartingaleGeneral
end MathFin
