/-
Copyright (c) 2026 Raphael Coelho. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Raphael Coelho
-/
module

public import Mathlib
public import MathFin.Foundations.PoissonRandomMeasure

/-!
# The compensated-Poisson isometry kernel (increment-independence cornerstone)

The jump analogue of `Foundations/ItoIsometryAdapted.lean`. For a Poisson random measure `N`,
the second-moment energy identities that the Itô–Lévy isometry sums are:

* diagonal `𝔼[φ² · Ñ(box)²] = 𝔼[φ²] · ν̂(box)` (`integral_adapted_sq_mul_compensated_sq`);
* cross `𝔼[φ · Ñ(box₁) · ψ · Ñ(box₂)] = 0` for disjoint boxes with `box₁` in the past-region
  of `box₂` (`integral_cross_compensated_eq_zero`).

Both flow from the single structure field `indep_of_disjoint_region` (independent scattering):
`N` on any region disjoint from `D` is independent of `N(·, D)`. The past `σ`-algebra at a time
`s` and the count on any box disjoint from a future box both live in that "disjoint region", so
one field closes every cross-term — the different-time cross pairs *and* the same-time /
different-mark cross pairs that a `time × mark` simple integrand produces.

## Provenance

Design mirrors our continuous `ItoIsometryAdapted`; the PRM object is from
`Foundations/PoissonRandomMeasure` (field shape consulted from `cgarryZA/LevyStochCalc`, cited).
The isometry content is our own — LevyStochCalc states it as cited axiom #6.
-/

@[expose] public section

namespace MathFin

open MeasureTheory ProbabilityTheory
open scoped NNReal ENNReal

variable {Ω : Type*} [MeasurableSpace Ω] {E : Type*} [MeasurableSpace E]
  {P : Measure Ω} [IsProbabilityMeasure P] {ν : Measure E} [SigmaFinite ν]

/-! ### The past and disjoint-region `σ`-algebras -/

/-- The **PRM past `σ`-algebra at time `s`** — generated by the counts on space-time sets
contained in `(-∞, s] × E`. -/
@[reducible] def PoissonRandomMeasure.pastSigma (N : PoissonRandomMeasure P ν) (s : ℝ) :
    MeasurableSpace Ω :=
  ⨆ C ∈ {C : Set (ℝ × E) | C ⊆ Set.Iic s ×ˢ Set.univ ∧ MeasurableSet C},
    MeasurableSpace.comap (fun ω => N.N ω C) inferInstance

/-- The **disjoint-region `σ`-algebra of `D`** — generated by the counts on all measurable
space-time sets disjoint from `D`. This is the left factor of the `indep_of_disjoint_region`
independence, made into a named object. -/
@[reducible] def PoissonRandomMeasure.regionSigma (N : PoissonRandomMeasure P ν)
    (D : Set (ℝ × E)) : MeasurableSpace Ω :=
  ⨆ C ∈ {C : Set (ℝ × E) | Disjoint C D ∧ MeasurableSet C},
    MeasurableSpace.comap (fun ω => N.N ω C) inferInstance

/-- `φ` is **adapted at `s`** if it is measurable for the PRM past `σ`-algebra at `s`. -/
def PoissonRandomMeasure.AdaptedAt (N : PoissonRandomMeasure P ν) (s : ℝ) (φ : Ω → ℝ) : Prop :=
  Measurable[N.pastSigma s] φ

omit [MeasurableSpace E] in
/-- Two space-time products with disjoint time-projections are disjoint. -/
private lemma disjoint_prod_time {I J : Set ℝ} (hIJ : Disjoint I J) (U V : Set E) :
    Disjoint (I ×ˢ U) (J ×ˢ V) := by
  rw [Set.disjoint_left]
  rintro z hz1 hz2
  exact (Set.disjoint_left.mp hIJ) (Set.mem_prod.mp hz1).1 (Set.mem_prod.mp hz2).1

/-- A past-set at `sa` is disjoint from a future box `(sb, tb] × Ab` when `sa ≤ sb`, and it
carries its measurability into membership of `regionSigma`'s index set. -/
private lemma pastSet_mem_regionSigma_index {sa sb tb : ℝ} (hab : sa ≤ sb) (Ab : Set E)
    {C : Set (ℝ × E)} (hC : C ⊆ Set.Iic sa ×ˢ Set.univ ∧ MeasurableSet C) :
    Disjoint C (Set.Ioc sb tb ×ˢ Ab) ∧ MeasurableSet C := by
  refine ⟨?_, hC.2⟩
  have hdt : Disjoint (Set.Iic sa) (Set.Ioc sb tb) := by
    rw [Set.disjoint_left]
    intro x hx1 hx2
    exact absurd (le_trans hx1 hab) (not_le.mpr (Set.mem_Ioc.mp hx2).1)
  exact Set.disjoint_of_subset hC.1 (Set.prod_mono le_rfl (Set.subset_univ Ab))
    (disjoint_prod_time hdt Set.univ Set.univ)

/-- `regionSigma D ≤ mΩ`: every generating count is `mΩ`-measurable. -/
private lemma regionSigma_le (N : PoissonRandomMeasure P ν) (D : Set (ℝ × E)) :
    N.regionSigma D ≤ (inferInstance : MeasurableSpace Ω) :=
  iSup₂_le fun _ hC => measurable_iff_comap_le.mp (N.measurable_eval hC.2)

/-- The past `σ`-algebra at `sa` sits inside the disjoint-region `σ`-algebra of a future
box `(sb, tb] × Ab`, for `sa ≤ sb`. -/
private lemma pastSigma_le_regionSigma (N : PoissonRandomMeasure P ν) {sa sb tb : ℝ}
    (hab : sa ≤ sb) (Ab : Set E) :
    N.pastSigma sa ≤ N.regionSigma (Set.Ioc sb tb ×ˢ Ab) :=
  iSup₂_le fun C hC => le_iSup₂_of_le C (pastSet_mem_regionSigma_index hab Ab hC) le_rfl

/-- The count on any measurable set disjoint from `D` lands in the disjoint-region
`σ`-algebra of `D`. -/
private lemma comap_le_regionSigma (N : PoissonRandomMeasure P ν) {Ba D : Set (ℝ × E)}
    (hdisj : Disjoint Ba D) (hBa : MeasurableSet Ba) :
    MeasurableSpace.comap (fun ω => N.N ω Ba) inferInstance ≤ N.regionSigma D :=
  le_iSup₂_of_le Ba ⟨hdisj, hBa⟩ le_rfl

/-! ### Measurability of adapted integrands and compensated increments -/

/-- An integrand adapted at `s` is (ambient-)measurable. -/
theorem PoissonRandomMeasure.AdaptedAt.measurable {N : PoissonRandomMeasure P ν} {s : ℝ}
    {φ : Ω → ℝ} (hφ : N.AdaptedAt s φ) : Measurable φ := by
  have hφ' : Measurable[N.pastSigma s] φ := hφ
  exact hφ'.mono (iSup₂_le fun _ hC => measurable_iff_comap_le.mp (N.measurable_eval hC.2)) le_rfl

/-- The reference intensity of a finite-mark box `(s,t] × A` is finite. -/
theorem referenceIntensity_box_ne_top {s t : ℝ} {A : Set E} (hAfin : ν A ≠ ⊤) :
    referenceIntensity ν (Set.Ioc s t ×ˢ A) ≠ ⊤ := by
  show ((volume.restrict (Set.Ici (0 : ℝ))).prod ν) (Set.Ioc s t ×ˢ A) ≠ ⊤
  rw [Measure.prod_prod]
  refine ENNReal.mul_ne_top ?_ hAfin
  rw [Measure.restrict_apply measurableSet_Ioc]
  exact ne_top_of_le_ne_top (by rw [Real.volume_Ioc]; exact ENNReal.ofReal_ne_top)
    (measure_mono Set.inter_subset_left)

/-- On a box `(a,b] × A` with `0 ≤ a ≤ b`, the reference intensity is `(b − a) · ν(A)` — the
`L²(dt ⊗ dν)`-weight one term of the isometry carries. -/
theorem referenceIntensity_box_toReal {a b : ℝ} (ha : 0 ≤ a) (hab : a ≤ b) {A : Set E} :
    (referenceIntensity ν (Set.Ioc a b ×ˢ A)).toReal = (b - a) * (ν A).toReal := by
  have hsub : Set.Ioc a b ⊆ Set.Ici (0 : ℝ) :=
    fun x hx => le_of_lt (lt_of_le_of_lt ha (Set.mem_Ioc.mp hx).1)
  have hval : referenceIntensity ν (Set.Ioc a b ×ˢ A) = ENNReal.ofReal (b - a) * ν A := by
    show ((volume.restrict (Set.Ici (0 : ℝ))).prod ν) (Set.Ioc a b ×ˢ A) = _
    rw [Measure.prod_prod, Measure.restrict_apply measurableSet_Ioc,
        Set.inter_eq_left.mpr hsub, Real.volume_Ioc]
  rw [hval, ENNReal.toReal_mul, ENNReal.toReal_ofReal (by linarith)]

/-! ### The independence cornerstone and the energy identities -/

/-- **Past-adapted `⟂` future compensated increment.** An integrand adapted at `s` is
independent of `Ñ((s,t] × A)`. Re-derived in one `indep_of_disjoint_region` step: the past
at `s` lives on `(-∞,s] × E`, which is disjoint from the future box `(s,t] × A`, so
`comap φ ≤ pastSigma s ≤ regionSigma((s,t] × A)`, and the field pairs that region against the
box count; then compose with `x ↦ x.toReal − ν̂(box)`. -/
theorem adapted_indepFun_compensated (N : PoissonRandomMeasure P ν) {s t : ℝ}
    {A : Set E} (hA : MeasurableSet A) {φ : Ω → ℝ} (hφ : N.AdaptedAt s φ) :
    IndepFun φ (N.compensated (Set.Ioc s t ×ˢ A)) P := by
  have hbox : MeasurableSet (Set.Ioc s t ×ˢ A) := measurableSet_Ioc.prod hA
  have hfield : Indep (N.regionSigma (Set.Ioc s t ×ˢ A))
      (MeasurableSpace.comap (fun ω => N.N ω (Set.Ioc s t ×ˢ A)) inferInstance) P :=
    N.indep_of_disjoint_region hbox
  have hφ' : Measurable[N.pastSigma s] φ := hφ
  have hφ_le : MeasurableSpace.comap φ inferInstance ≤ N.regionSigma (Set.Ioc s t ×ˢ A) :=
    le_trans (measurable_iff_comap_le.mp hφ') (pastSigma_le_regionSigma N le_rfl A)
  have hraw : IndepFun φ (fun ω => N.N ω (Set.Ioc s t ×ˢ A)) P :=
    (IndepFun_iff_Indep _ _ _).mpr (indep_of_indep_of_le_left hfield hφ_le)
  have hcomp := hraw.comp (φ := (id : ℝ → ℝ))
    (ψ := fun x : ℝ≥0∞ => x.toReal - (referenceIntensity ν (Set.Ioc s t ×ˢ A)).toReal)
    measurable_id (by fun_prop)
  simp only [Function.comp_def, id_eq] at hcomp
  exact hcomp

/-- **Zero-pairing against a fresh compensated increment.** If `X` is measurable for the
disjoint-region `σ`-algebra of `D`, then `𝔼[X · Ñ(D)] = 0`: `X ⟂ Ñ(D)` (independent
scattering) and `Ñ(D)` is mean-zero. This is the single engine behind every cross-term. -/
theorem integral_mul_compensated_eq_zero (N : PoissonRandomMeasure P ν) {D : Set (ℝ × E)}
    (hD : MeasurableSet D) (hfin : referenceIntensity ν D ≠ ⊤)
    {X : Ω → ℝ} (hX : Measurable[N.regionSigma D] X) :
    ∫ ω, X ω * N.compensated D ω ∂P = 0 := by
  have hXm : Measurable X := hX.mono (regionSigma_le N D) le_rfl
  have hfield : Indep (N.regionSigma D)
      (MeasurableSpace.comap (fun ω => N.N ω D) inferInstance) P := N.indep_of_disjoint_region hD
  have hraw : IndepFun X (fun ω => N.N ω D) P :=
    (IndepFun_iff_Indep _ _ _).mpr (indep_of_indep_of_le_left hfield (measurable_iff_comap_le.mp hX))
  have hcomp : IndepFun X (N.compensated D) P := by
    have h := hraw.comp (φ := (id : ℝ → ℝ))
      (ψ := fun x : ℝ≥0∞ => x.toReal - (referenceIntensity ν D).toReal) measurable_id (by fun_prop)
    simp only [Function.comp_def, id_eq] at h
    exact h
  rw [hcomp.integral_fun_mul_eq_mul_integral hXm.aestronglyMeasurable
        (N.measurable_compensated hD).aestronglyMeasurable,
      compensated_integral_zero N hD hfin, mul_zero]

/-- **Diagonal energy** (the isometry's diagonal term): for `φ` adapted at `s`,
`𝔼[φ² · Ñ((s,t] × A)²] = 𝔼[φ²] · ν̂((s,t] × A)`. The increment's square is independent of
the past (`adapted_indepFun_compensated`, squared) and has mean `ν̂(box)`
(`compensated_integral_sq`). -/
theorem integral_adapted_sq_mul_compensated_sq (N : PoissonRandomMeasure P ν)
    {s t : ℝ} {A : Set E} (hA : MeasurableSet A) (hAfin : ν A ≠ ⊤)
    {φ : Ω → ℝ} (hφ : N.AdaptedAt s φ) :
    ∫ ω, (φ ω) ^ 2 * (N.compensated (Set.Ioc s t ×ˢ A) ω) ^ 2 ∂P
      = (∫ ω, (φ ω) ^ 2 ∂P) * (referenceIntensity ν (Set.Ioc s t ×ˢ A)).toReal := by
  have hbox : MeasurableSet (Set.Ioc s t ×ˢ A) := measurableSet_Ioc.prod hA
  have hfin : referenceIntensity ν (Set.Ioc s t ×ˢ A) ≠ ⊤ := referenceIntensity_box_ne_top hAfin
  have hφm : Measurable φ := hφ.measurable
  have hÑm : Measurable (N.compensated (Set.Ioc s t ×ˢ A)) := N.measurable_compensated hbox
  have hindep : IndepFun φ (N.compensated (Set.Ioc s t ×ˢ A)) P :=
    adapted_indepFun_compensated N hA hφ
  have hindep2 := hindep.comp (φ := fun x : ℝ => x ^ 2) (ψ := fun x : ℝ => x ^ 2)
    (by fun_prop) (by fun_prop)
  have key := hindep2.integral_fun_mul_eq_mul_integral (hφm.pow_const 2).aestronglyMeasurable
    (hÑm.pow_const 2).aestronglyMeasurable
  simp only [Function.comp_apply] at key
  rw [key, compensated_integral_sq N hbox hfin]

/-- **Cross-term vanishing** (both cross families of a `time × mark` simple integrand). For
`φa` adapted at `sa`, `φb` adapted at `sb` with `sa ≤ sb`, a measurable `Ba` disjoint from the
future box `(sb, tb] × Ab`,

  `𝔼[(φa · Ñ(Ba)) · (φb · Ñ((sb,tb] × Ab))] = 0`.

The first factor `φa · Ñ(Ba) · φb` is measurable for `regionSigma((sb,tb] × Ab)` — `φa`, `φb`
past-adapted (their pasts precede the box), `Ñ(Ba)` on a disjoint box — so it pairs to zero
against the fresh increment by `integral_mul_compensated_eq_zero`. Different-time cross pairs
take `Ba = (sa, ta] × Aa` with `ta ≤ sb`; same-time / different-mark pairs take
`Ba = (sb, tb] × Aa` with `Aa ∩ Ab = ∅`. -/
theorem integral_cross_compensated_eq_zero (N : PoissonRandomMeasure P ν)
    {sa sb tb : ℝ} (hab : sa ≤ sb)
    {Ba : Set (ℝ × E)} (hBa : MeasurableSet Ba) {Ab : Set E} (hAb : MeasurableSet Ab)
    (hAbfin : ν Ab ≠ ⊤) (hdisj : Disjoint Ba (Set.Ioc sb tb ×ˢ Ab))
    {φa φb : Ω → ℝ} (hφa : N.AdaptedAt sa φa) (hφb : N.AdaptedAt sb φb) :
    ∫ ω, (φa ω * N.compensated Ba ω)
          * (φb ω * N.compensated (Set.Ioc sb tb ×ˢ Ab) ω) ∂P = 0 := by
  have hboxbms : MeasurableSet (Set.Ioc sb tb ×ˢ Ab) := measurableSet_Ioc.prod hAb
  have hfin : referenceIntensity ν (Set.Ioc sb tb ×ˢ Ab) ≠ ⊤ := referenceIntensity_box_ne_top hAbfin
  have hφa' : Measurable[N.pastSigma sa] φa := hφa
  have hφb' : Measurable[N.pastSigma sb] φb := hφb
  have hXa : Measurable[N.regionSigma (Set.Ioc sb tb ×ˢ Ab)] φa :=
    hφa'.mono (pastSigma_le_regionSigma N hab Ab) le_rfl
  have hXÑa : Measurable[N.regionSigma (Set.Ioc sb tb ×ˢ Ab)] (N.compensated Ba) := by
    show Measurable[N.regionSigma (Set.Ioc sb tb ×ˢ Ab)]
      fun ω => (N.N ω Ba).toReal - (referenceIntensity ν Ba).toReal
    have hc : Measurable[N.regionSigma (Set.Ioc sb tb ×ˢ Ab)] fun ω => N.N ω Ba :=
      (measurable_iff_comap_le.mpr le_rfl).mono (comap_le_regionSigma N hdisj hBa) le_rfl
    exact hc.ennreal_toReal.sub measurable_const
  have hXb : Measurable[N.regionSigma (Set.Ioc sb tb ×ˢ Ab)] φb :=
    hφb'.mono (pastSigma_le_regionSigma N le_rfl Ab) le_rfl
  have hX : Measurable[N.regionSigma (Set.Ioc sb tb ×ˢ Ab)]
      fun ω => φa ω * N.compensated Ba ω * φb ω := (hXa.mul hXÑa).mul hXb
  have hzero := integral_mul_compensated_eq_zero N hboxbms hfin hX
  rw [← hzero]
  exact integral_congr_ae (Filter.Eventually.of_forall fun ω => by ring)

/-- **Each simple-integrand term is `L²`.** For `φ` adapted at `s` and in `L²`, the term
`φ · Ñ((s,t] × A) ∈ L²(P)`: the increment is `L²` (`memLp_compensated`) and independent of the
`L²` coefficient `φ`, so the product's square is integrable. -/
theorem memLp_adapted_mul_compensated (N : PoissonRandomMeasure P ν) {s t : ℝ}
    {A : Set E} (hA : MeasurableSet A) (hAfin : ν A ≠ ⊤)
    {φ : Ω → ℝ} (hφ : N.AdaptedAt s φ) (hφL2 : MemLp φ 2 P) :
    MemLp (fun ω => φ ω * N.compensated (Set.Ioc s t ×ˢ A) ω) 2 P := by
  have hbox : MeasurableSet (Set.Ioc s t ×ˢ A) := measurableSet_Ioc.prod hA
  have hfin : referenceIntensity ν (Set.Ioc s t ×ˢ A) ≠ ⊤ := referenceIntensity_box_ne_top hAfin
  have hφm : Measurable φ := hφ.measurable
  have hÑm : Measurable (N.compensated (Set.Ioc s t ×ˢ A)) := N.measurable_compensated hbox
  have hindep : IndepFun φ (N.compensated (Set.Ioc s t ×ˢ A)) P :=
    adapted_indepFun_compensated N hA hφ
  have hφsq : Integrable (fun ω => (φ ω) ^ 2) P := hφL2.integrable_sq
  have hÑsq : Integrable (fun ω => (N.compensated (Set.Ioc s t ×ˢ A) ω) ^ 2) P :=
    (memLp_compensated N hbox hfin).integrable_sq
  have hindep2 := hindep.comp (φ := fun x : ℝ => x ^ 2) (ψ := fun x : ℝ => x ^ 2)
    (by fun_prop) (by fun_prop)
  have hprod : Integrable
      (fun ω => (φ ω) ^ 2 * (N.compensated (Set.Ioc s t ×ˢ A) ω) ^ 2) P :=
    hindep2.integrable_mul hφsq hÑsq
  refine (memLp_two_iff_integrable_sq (hφm.mul hÑm).aestronglyMeasurable).mpr ?_
  simpa [mul_pow] using hprod

end MathFin
