import SharpWasserstein.BrownianNoise

/-! Continuous paths carry exactly the sigma-algebra generated by their
coordinate evaluations. This transports proved process laws and independence
to the actual continuous-path spaces used by the flow construction. -/
noncomputable section
open MeasureTheory ProbabilityTheory
namespace SharpWasserstein

variable {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]
  [SecondCountableTopology X] [SecondCountableTopology Y] [LocallyCompactSpace X]
  [RegularSpace Y] [MeasurableSpace Y] [BorelSpace Y]

theorem continuousPath_measurableSpace_eq_comap :
    (inferInstance : MeasurableSpace C(X,Y)) =
      (inferInstance : MeasurableSpace (X → Y)).comap (fun f : C(X,Y) => (f : X → Y)) := by
  rw [ContinuousMap.measurableSpace_eq_iSup_comap_eval]
  simp only [MeasurableSpace.pi,MeasurableSpace.comap_iSup,MeasurableSpace.comap_comp]
  rfl

omit [SecondCountableTopology X] [SecondCountableTopology Y] [LocallyCompactSpace X] [RegularSpace Y] in
theorem continuousPath_coe_measurable : Measurable (fun f : C(X,Y) => (f : X → Y)) :=
  measurable_pi_lambda _ fun x => (continuous_eval_const x).measurable

/-- Equality of the genuine function-process laws implies equality of the
continuous-path laws; no path-law uniqueness axiom is used. -/
theorem continuousPath_map_coe_injective : Function.Injective
    (Measure.map (fun f : C(X,Y) => (f : X → Y))) := by
  intro μ ν h
  apply Measure.ext
  intro s hs
  have hs' : MeasurableSet[(inferInstance : MeasurableSpace (X → Y)).comap
      (fun f : C(X,Y) => (f : X → Y))] s := by
    rw [← continuousPath_measurableSpace_eq_comap]
    exact hs
  obtain ⟨u,hu,rfl⟩ := hs'
  have he := congrArg (fun η : Measure (X → Y) => η u) h
  simpa only [Measure.map_apply continuousPath_coe_measurable hu] using he

/-- Independence of the evaluation processes is exactly independence of
the continuous random paths. -/
theorem continuousPath_indepFun_of_coe {Ω X' Y' : Type*} [MeasurableSpace Ω]
    [TopologicalSpace X'] [TopologicalSpace Y'] [SecondCountableTopology X']
    [SecondCountableTopology Y'] [LocallyCompactSpace X'] [RegularSpace Y']
    [MeasurableSpace Y'] [BorelSpace Y'] {P : Measure Ω}
    (F : Ω → C(X,Y)) (G : Ω → C(X',Y'))
    (h : IndepFun (fun ω => (F ω : X → Y)) (fun ω => (G ω : X' → Y')) P) : IndepFun F G P := by
  rw [IndepFun_iff_Indep] at h ⊢
  simpa only [continuousPath_measurableSpace_eq_comap,MeasurableSpace.comap_comp,Function.comp_def] using h

end SharpWasserstein
