import SharpWasserstein.VolterraFourierRecovery
import SharpWasserstein.VolterraFourierLimit
import SharpWasserstein.VolterraFourierHierarchy
import SharpWasserstein.VolterraFourierSource
import SharpWasserstein.VolterraFourierSourceHierarchy

#print axioms SharpWasserstein.VolterraFourier.finiteEnergy
#print axioms SharpWasserstein.VolterraFourier.totalEnergy
#print axioms SharpWasserstein.VolterraFourier.gap
#print axioms SharpWasserstein.VolterraFourier.finiteEnergy_nonneg
#print axioms SharpWasserstein.VolterraFourier.finiteEnergy_le
#print axioms SharpWasserstein.VolterraFourier.gap_bounds
#print axioms SharpWasserstein.VolterraFourier.finiteEnergy_tendsto
#print axioms SharpWasserstein.VolterraFourier.totalEnergy_aestronglyMeasurable
#print axioms SharpWasserstein.VolterraFourier.totalEnergy_integrable
#print axioms SharpWasserstein.VolterraFourier.finiteEnergy_integrable
#print axioms SharpWasserstein.VolterraFourier.gap_integrable
#print axioms SharpWasserstein.VolterraFourier.integral_norm_gap_tendsto
#print axioms SharpWasserstein.VolterraFourier.integral_norm_mul_gap_tendsto
#print axioms SharpWasserstein.VolterraFourier.totalEnergy_intervalIntegrable
#print axioms SharpWasserstein.VolterraFourier.intervalIntegral_norm_mul_gap_tendsto
#print axioms SharpWasserstein.VolterraFourier.volterra_bound_of_finite_derivative
#print axioms SharpWasserstein.VolterraFourier.intervalIntegrable_prefix
#print axioms SharpWasserstein.VolterraFourier.hierarchy_of_finite_derivatives
#print axioms SharpWasserstein.VolterraFourier.quadratic_bound_of_finite_derivatives
#print axioms SharpWasserstein.VolterraFourier.quadratic_bound_of_finite_derivatives_bounded_coefficients
#print axioms SharpWasserstein.VolterraFourier.sourceRepresentative
#print axioms SharpWasserstein.VolterraFourier.sourceFiniteEnergy
#print axioms SharpWasserstein.VolterraFourier.sourceRepresentative_mem
#print axioms SharpWasserstein.VolterraFourier.totalEnergy_sourceRepresentative
#print axioms SharpWasserstein.VolterraFourier.sourceEnergy_aestronglyMeasurable
#print axioms SharpWasserstein.VolterraFourier.sourceEnergy_integrable_of_full_bound
#print axioms SharpWasserstein.VolterraFourier.source_gap_tendsto_of_full_bound
#print axioms SharpWasserstein.VolterraFourier.source_quadratic_bound_of_finite_derivatives
