import SharpWasserstein.RegularizedBrownianSourceCoordinates
import SharpWasserstein.RegularizedBrownianSourceData
import SharpWasserstein.RegularizedBrownianSourceBound
import SharpWasserstein.RegularizedBrownianSourceSwitch

#print axioms SharpWasserstein.RegularizedBrownianSource.energy_measure_congr
#print axioms SharpWasserstein.RegularizedBrownianSource.levelEnergy_eq_configurationMarginal
#print axioms SharpWasserstein.RegularizedBrownianSource.initialCurrent_distribution_pairing
#print axioms SharpWasserstein.RegularizedBrownianSource.law_probability
#print axioms SharpWasserstein.RegularizedBrownianSource.law_secondMoment
#print axioms SharpWasserstein.RegularizedBrownianSource.law_exchangeable
#print axioms SharpWasserstein.RegularizedBrownianSource.current_memLp
#print axioms SharpWasserstein.RegularizedBrownianSource.current_covariant
#print axioms SharpWasserstein.RegularizedBrownianSource.exists_initial_profile
#print axioms SharpWasserstein.RegularizedBrownianSource.propagationConstant
#print axioms SharpWasserstein.RegularizedBrownianSource.sourceHorizonConstant_nonneg
#print axioms SharpWasserstein.RegularizedBrownianSource.propagationConstant_nonneg
#print axioms SharpWasserstein.RegularizedBrownianSource.prefixEnergy_le
#print axioms SharpWasserstein.RegularizedBrownianSource.imageEnergy_measure_congr
#print axioms SharpWasserstein.RegularizedBrownianSource.prescribed_marginal_energy_eq_prefix
#print axioms SharpWasserstein.RegularizedBrownianSource.prescribed_marginal_energy_le
