import SharpWasserstein.ExternalInteractionSymmetry
import SharpWasserstein.ExternalInteractionSymmetryAverage
import SharpWasserstein.ExternalInteractionSymmetryMarginal
import SharpWasserstein.ExternalInteractionSymmetryEstimate
#print axioms SharpWasserstein.ExternalInteractionSymmetry.observation
#print axioms SharpWasserstein.ExternalInteractionSymmetry.observation_prefix
#print axioms SharpWasserstein.ExternalInteractionSymmetry.observation_positions
#print axioms SharpWasserstein.ExternalInteractionSymmetry.observation_external
#print axioms SharpWasserstein.ExternalInteractionSymmetry.observation_permutation
#print axioms SharpWasserstein.ExternalInteractionSymmetry.external_swap_fixes_prefix
#print axioms SharpWasserstein.ExternalInteractionSymmetry.observation_test_swap
#print axioms SharpWasserstein.ExternalInteractionSymmetry.particleInteraction
#print axioms SharpWasserstein.ExternalInteractionSymmetry.particleInteraction_eq_sum
#print axioms SharpWasserstein.ExternalInteractionSymmetry.particleInteraction_fderiv
#print axioms SharpWasserstein.ExternalInteractionSymmetry.pairing
#print axioms SharpWasserstein.ExternalInteractionSymmetry.pairing_invariant
#print axioms SharpWasserstein.ExternalInteractionSymmetry.external_pairing_eq
#print axioms SharpWasserstein.ExternalInteractionSymmetry.external_card
#print axioms SharpWasserstein.ExternalInteractionSymmetry.external_pairing_sum
#print axioms SharpWasserstein.ExternalInteractionSymmetry.external_pairing_meanField
#print axioms SharpWasserstein.ExternalInteractionSymmetry.external_pairing_terminal
#print axioms SharpWasserstein.ExternalInteractionSymmetry.canonical_external_pairing_meanField
#print axioms SharpWasserstein.ExternalInteractionSymmetry.randomSource_closed_pairing
#print axioms SharpWasserstein.ExternalInteractionSymmetry.randomSource_bounded_pairing
#print axioms SharpWasserstein.ExternalInteractionSymmetry.observedVelocity
#print axioms SharpWasserstein.ExternalInteractionSymmetry.observedVelocity_ae
#print axioms SharpWasserstein.ExternalInteractionSymmetry.observedSource
#print axioms SharpWasserstein.ExternalInteractionSymmetry.observedSource_finiteEnergy
#print axioms SharpWasserstein.ExternalInteractionSymmetry.observedSource_apply
#print axioms SharpWasserstein.ExternalInteractionSymmetry.observedSource_bounded_pairing
#print axioms SharpWasserstein.ExternalInteractionSymmetry.external_pairing_meanField_marginal
#print axioms SharpWasserstein.ExternalInteractionSymmetry.interaction_bounded_gradient
#print axioms SharpWasserstein.ExternalInteractionSymmetry.compact_interaction_bounded_gradient
#print axioms SharpWasserstein.ExternalInteractionSymmetry.external_interaction_meanField_marginal
