import SharpWasserstein.RoughEulerianSpaceTimeEquation
#print axioms SharpWasserstein.RoughEulerianSmoothing.spaceTimeFlux_test_pairing
#print axioms SharpWasserstein.RoughEulerianSmoothing.regularizedLaw_test_pairing
#print axioms SharpWasserstein.RoughEulerianSmoothing.time_weighted_joint_pairing_integrable
#print axioms SharpWasserstein.RoughEulerianSmoothing.spaceTimeRegularizedLaw_test_pairing
#print axioms SharpWasserstein.RoughEulerianSmoothing.spaceTimeRegularizedLaw_flux_pairing
#print axioms SharpWasserstein.RoughEulerianSmoothing.spaceTimeVelocity
#print axioms SharpWasserstein.RoughEulerianSmoothing.joint_gradient_pairing_integrable
#print axioms SharpWasserstein.RoughEulerianSmoothing.spaceTimeRegularizedLaw_flux_continuous
#print axioms SharpWasserstein.RoughEulerianSmoothing.spaceTimeRegularizedLaw_hasDerivAt
#print axioms SharpWasserstein.RoughEulerianSmoothing.spaceTimeProbabilityCurve_equation
