import SharpWasserstein.InitialSourceMarginalPairing
import SharpWasserstein.InitialSourceMarginalComposition
import SharpWasserstein.InitialSourceMarginalConfiguration
import SharpWasserstein.InitialSourceMarginalCurrent
import SharpWasserstein.InitialSourceMarginalPrefix
import SharpWasserstein.InitialSourceMarginalRegularized

#print axioms SharpWasserstein.InitialSourceMarginal.representative_bounded_pairing
#print axioms SharpWasserstein.InitialSourceMarginal.imageSource
#print axioms SharpWasserstein.InitialSourceMarginal.imageSource_finite
#print axioms SharpWasserstein.InitialSourceMarginal.imageSource_apply
#print axioms SharpWasserstein.InitialSourceMarginal.cylinder_bounds
#print axioms SharpWasserstein.InitialSourceMarginal.imageSource_eq_flux_pairing
#print axioms SharpWasserstein.InitialSourceMarginal.imageSource_prefix_eq
#print axioms SharpWasserstein.InitialSourceMarginal.imageSource_comp
#print axioms SharpWasserstein.InitialSourceMarginal.map_marginalProjection
#print axioms SharpWasserstein.InitialSourceMarginal.configurationMarginalSource
#print axioms SharpWasserstein.InitialSourceMarginal.euclideanDistribution_configurationMarginalSource
#print axioms SharpWasserstein.InitialSourceMarginal.configurationMarginalSource_finite
#print axioms SharpWasserstein.InitialSourceMarginal.initialCurrent_memLp
#print axioms SharpWasserstein.InitialSourceMarginal.source_eq_configurationFlux
#print axioms SharpWasserstein.InitialSourceMarginal.configurationMarginalSource_apply_current
#print axioms SharpWasserstein.InitialSourceMarginal.configurationMarginalSource_self
#print axioms SharpWasserstein.InitialSourceMarginal.integrable_bounded_mul
#print axioms SharpWasserstein.InitialSourceMarginal.reference_coordinate_measurable
#print axioms SharpWasserstein.InitialSourceMarginal.reference_coordinate_bound
#print axioms SharpWasserstein.InitialSourceMarginal.particle_coordinate_measurable
#print axioms SharpWasserstein.InitialSourceMarginal.particle_coordinate_bounded
#print axioms SharpWasserstein.InitialSourceMarginal.conditional_coordinate_measurable
#print axioms SharpWasserstein.InitialSourceMarginal.conditional_coordinate_bounded
#print axioms SharpWasserstein.InitialSourceMarginal.integral_current_eq_conditional
#print axioms SharpWasserstein.InitialSourceMarginal.bounded_sub
#print axioms SharpWasserstein.InitialSourceMarginal.configurationMarginalSource_generator
#print axioms SharpWasserstein.InitialSourceMarginal.configurationMarginalSource_eq
#print axioms SharpWasserstein.InitialSourceMarginal.dimensionReindex
#print axioms SharpWasserstein.InitialSourceMarginal.prefix_comp_dimensionReindex
#print axioms SharpWasserstein.InitialSourceMarginal.marginalDistribution_reindexed_eq
#print axioms SharpWasserstein.InitialSourceMarginal.marginalLaw_reindexed_eq
#print axioms SharpWasserstein.InitialSourceMarginal.marginal_energy_reindexed_eq
#print axioms SharpWasserstein.InitialSourceMarginal.exists_regularized_consistent_source
#print axioms SharpWasserstein.InitialSourceMarginal.exists_regularized_weighted_marginal_profile
