import SharpWasserstein.RoughUniformActionData
import SharpWasserstein.RoughEulerianRegularizedTransport
import SharpWasserstein.RoughUniformRegularizedTransport

#print axioms SharpWasserstein.RoughUniformAction.compressedJoint
#print axioms SharpWasserstein.RoughUniformAction.compressedField
#print axioms SharpWasserstein.RoughUniformAction.compressedJoint_eq
#print axioms SharpWasserstein.RoughUniformAction.compressedField_integrable
#print axioms SharpWasserstein.RoughUniformAction.compressedField_sq_integrable
#print axioms SharpWasserstein.RoughUniformAction.compressedJoint_support
#print axioms SharpWasserstein.RoughUniformAction.integral_constant_horizon
#print axioms SharpWasserstein.RoughUniformAction.compressedField_action_le
#print axioms SharpWasserstein.RoughUniformAction.compressedField_restricted_action_le
#print axioms SharpWasserstein.RoughUniformAction.compressedField_equation
#print axioms SharpWasserstein.RoughEulerianSmoothing.spaceTimeRegularizedLaw_wassersteinSq_le
#print axioms SharpWasserstein.RoughUniformAction.compressed_regularized_wassersteinSq_le
