import SharpWasserstein.BrownianEnergyPeriodizationIdentification
import SharpWasserstein.BrownianEnergyPeriodizationExhaustion
import SharpWasserstein.BrownianEnergyPeriodizationLimit
import SharpWasserstein.BrownianEnergyPeriodizationPeriodic
import SharpWasserstein.BrownianEnergyPeriodization
#print axioms SharpWasserstein.BrownianEnergyPeriodization.fullLaw_eq_brownianLawAt
#print axioms SharpWasserstein.BrownianEnergyPeriodization.projectedLaw_eq_map_fullLaw
#print axioms SharpWasserstein.BrownianEnergyPeriodization.projectedSource_eq_imageSource_full
#print axioms SharpWasserstein.BrownianEnergyPeriodization.projectedSource_eq_brownianImage
#print axioms SharpWasserstein.BrownianEnergyPeriodization.projectedLaw_eq_brownianMap
#print axioms SharpWasserstein.BrownianEnergyPeriodization.full_energy_le_of_kernel_periods
#print axioms SharpWasserstein.BrownianEnergyPeriodization.carryingLaw
#print axioms SharpWasserstein.BrownianEnergyPeriodization.propagatedSource
#print axioms SharpWasserstein.BrownianEnergyPeriodization.prefixEnergy
#print axioms SharpWasserstein.BrownianEnergyPeriodization.prefixEnergy_eq_projectedEnergy
#print axioms SharpWasserstein.BrownianEnergyPeriodization.prefixEnergy_le_of_sine_bounds
#print axioms SharpWasserstein.BrownianEnergyPeriodization.periodic_prefixEnergy_quadratic_bound
#print axioms SharpWasserstein.BrownianEnergyPeriodization.prefixEnergy_quadratic_bound
#print axioms SharpWasserstein.BrownianEnergyPeriodization.projectedSource_quadratic_bound
