import SharpWasserstein.WeightedPeriodicCoefficientEvolution
import SharpWasserstein.WeightedPeriodicCoefficientEvolutionBrownian
import SharpWasserstein.WeightedPeriodicCoefficientEvolutionFourier

#print axioms SharpWasserstein.WeightedPeriodicCoefficientEvolution.gradient_allDerivativesBounded
#print axioms SharpWasserstein.WeightedPeriodicCoefficientEvolution.gramTest
#print axioms SharpWasserstein.WeightedPeriodicCoefficientEvolution.gramTest_smooth
#print axioms SharpWasserstein.WeightedPeriodicCoefficientEvolution.gramTest_allDerivativesBounded
#print axioms SharpWasserstein.WeightedPeriodicCoefficientEvolution.gramEntry
#print axioms SharpWasserstein.WeightedPeriodicCoefficientEvolution.gramTest_integrable
#print axioms SharpWasserstein.WeightedPeriodicCoefficientEvolution.integral_map_euclidean
#print axioms SharpWasserstein.WeightedPeriodicCoefficientEvolution.observable_hasDerivWithinAt
#print axioms SharpWasserstein.WeightedPeriodicCoefficientEvolution.observable_hasDerivAt
#print axioms SharpWasserstein.WeightedPeriodicCoefficientEvolution.gramEntry_hasDerivWithinAt
#print axioms SharpWasserstein.WeightedPeriodicCoefficientEvolution.gramEntry_hasDerivAt
#print axioms SharpWasserstein.WeightedPeriodicCoefficientEvolution.gramEntry_derivative_continuousOn
#print axioms SharpWasserstein.WeightedPeriodicCoefficientEvolution.brownian_observable_hasDerivWithinAt
#print axioms SharpWasserstein.WeightedPeriodicCoefficientEvolution.brownian_observable_hasDerivAt
#print axioms SharpWasserstein.WeightedPeriodicCoefficientEvolution.brownian_gramEntry_hasDerivWithinAt
#print axioms SharpWasserstein.WeightedPeriodicCoefficientEvolution.brownian_gramEntry_hasDerivAt
#print axioms SharpWasserstein.WeightedPeriodicCoefficientEvolution.brownian_gramEntry_derivative_continuousOn
#print axioms SharpWasserstein.WeightedPeriodicCoefficientEvolution.brownian_source_derivative_continuousOn
#print axioms SharpWasserstein.WeightedPeriodicCoefficientEvolution.brownian_coefficients_hasDerivWithinAt
#print axioms SharpWasserstein.WeightedPeriodicCoefficientEvolution.periodic_allDerivativesBounded
#print axioms SharpWasserstein.WeightedPeriodicCoefficientEvolution.periodic_pullback_allDerivativesBounded
#print axioms SharpWasserstein.WeightedPeriodicCoefficientEvolution.atom_pullback_smooth
#print axioms SharpWasserstein.WeightedPeriodicCoefficientEvolution.atom_pullback_allDerivativesBounded
#print axioms SharpWasserstein.WeightedPeriodicCoefficientEvolution.frequencySpace_pullback_smooth_bounded
#print axioms SharpWasserstein.WeightedPeriodicCoefficientEvolution.frequencySpace_gramTest_smooth_bounded
