import SharpWasserstein.RoughEulerianTransportJointRegularity
#print axioms SharpWasserstein.RoughEulerianTransport.spatial_inclusion_hasFDerivAt
#print axioms SharpWasserstein.RoughEulerianTransport.spatial_fderiv
#print axioms SharpWasserstein.RoughEulerianTransport.spatial_allDerivativesBounded
#print axioms SharpWasserstein.RoughEulerianTransport.joint_spatial_regular
#print axioms SharpWasserstein.RoughEulerianTransport.EuclideanCompactWeakContinuity.wassersteinSq_le_finiteAction_of_joint_smooth
#print axioms SharpWasserstein.RoughEulerianTransport.spaceTimeFloorVelocity_spatial_regular
