import SharpWasserstein.RoughEulerianTimeActionLaw
import SharpWasserstein.RoughEulerianTimeActionConvolution
import SharpWasserstein.RoughEulerianTimeActionProduct
import SharpWasserstein.RoughEulerianTimeActionIdentification

#print axioms SharpWasserstein.RoughEulerianTime.timeWeight
#print axioms SharpWasserstein.RoughEulerianTime.timeWeight_measurable
#print axioms SharpWasserstein.RoughEulerianTime.weightedTimeKernel
#print axioms SharpWasserstein.RoughEulerianTime.weightedTimeKernel_apply
#print axioms SharpWasserstein.RoughEulerianTime.averagedKernel
#print axioms SharpWasserstein.RoughEulerianTime.averagedKernel_apply
#print axioms SharpWasserstein.RoughEulerianTime.integral_weightedTimeKernel
#print axioms SharpWasserstein.RoughEulerianTime.integral_averagedKernel
#print axioms SharpWasserstein.RoughEulerianTime.averagedKernel_probability
#print axioms SharpWasserstein.RoughEulerianTime.averagedKernel_support
#print axioms SharpWasserstein.RoughEulerianTime.kernel_smul_joint_integrable
#print axioms SharpWasserstein.RoughEulerianTime.integral_kernel_mul
#print axioms SharpWasserstein.RoughEulerianTime.kernel_mul_integrable
#print axioms SharpWasserstein.RoughEulerianTime.kernel_floor_action_le
#print axioms SharpWasserstein.RoughEulerianTime.kernel_floor_action_integrable_and_le
#print axioms SharpWasserstein.RoughEulerianSmoothing.spaceTimeKernel_integrable
#print axioms SharpWasserstein.RoughEulerianSmoothing.spaceTimeKernel_integral
#print axioms SharpWasserstein.RoughEulerianSmoothing.integral_spaceTimeKernel_mul
#print axioms SharpWasserstein.RoughEulerianSmoothing.spaceTimeFloor_action_integrable_and_le
#print axioms SharpWasserstein.RoughEulerianSmoothing.spaceTimeFloor_action_time_restrict
#print axioms SharpWasserstein.RoughEulerianSmoothing.spaceTimeDensity_eq_averaged
#print axioms SharpWasserstein.RoughEulerianSmoothing.spaceTimeFlux_eq_weighted
#print axioms SharpWasserstein.RoughEulerianSmoothing.spaceTimeRegularizedLaw
#print axioms SharpWasserstein.RoughEulerianSmoothing.spaceTimeRegularizedLaw_eq
#print axioms SharpWasserstein.RoughEulerianSmoothing.spaceTimeRegularizedLaw_probability
#print axioms SharpWasserstein.RoughEulerianSmoothing.spaceTimeRegularizedLaw_action_eq
#print axioms SharpWasserstein.RoughEulerianSmoothing.spaceTimeRegularizedLaw_action_integrable_and_le
