"""Generate formalization.yaml (mathlib-initiative v0.4) from the repo.

The file = MECHANICAL truth generated here (counts, axioms, sorry=0, the
divergence taxonomy, per-domain alignment) ⊕ EDITORIAL side-car
(`tools/formalization_meta.toml`: bibliography, headline results, reviewers).
The generator never invents editorial fields, and reads ONLY main-repo sources
(benchmarks + the side-car) — it has no dependency on the foundry, so the main
repo self-reports independently.

Benchmark entries may set ``metadata.alignment_source``. Distinct explicit
sources are joined per file; files without one retain the legacy domain/textbook
label.

Per the standard, mechanically-git-derivable facts (toolchain, pins, commit,
build status) are intentionally NOT duplicated here.

  python3 -m tools.formalization_yaml --write     # regenerate formalization.yaml
  python3 -m tools.formalization_yaml --check      # exit 1 if stale (CI gate)

Stdlib only (hand-rolled YAML emitter; tomllib for the side-car).
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import sys

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover
    tomllib = None

AXIOMS = ["propext", "Classical.choice", "Quot.sound"]
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "formalization.yaml")


# --- minimal YAML emitter -----------------------------------------------------

def _needs_quote(s: str) -> bool:
    if s == "" or s.strip() != s:
        return True
    if s[0] in "?-:#{}[],&*!|>%@`\"'":
        return True
    if ": " in s or " #" in s or "\n" in s:
        return True
    if s.lower() in ("null", "true", "false", "yes", "no", "~", "on", "off"):
        return True
    try:
        float(s)
        return True
    except ValueError:
        return False


def _scalar(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if v is None:
        return '""'
    s = str(v)
    if _needs_quote(s):
        return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return s


def _emit(obj, indent=0) -> list[str]:
    pad = "  " * indent
    lines: list[str] = []
    if isinstance(obj, dict):
        for k, v in obj.items():
            if isinstance(v, (dict, list)) and v:
                lines.append(f"{pad}{k}:")
                lines += _emit(v, indent + 1)
            elif isinstance(v, (dict, list)):
                lines.append(f"{pad}{k}: {'{}' if isinstance(v, dict) else '[]'}")
            else:
                lines.append(f"{pad}{k}: {_scalar(v)}")
    elif isinstance(obj, list):
        for item in obj:
            if isinstance(item, dict) and item:
                inner = _emit(item, indent + 1)
                lines.append(f"{pad}- {inner[0].strip()}")
                lines += inner[1:]
            else:
                lines.append(f"{pad}- {_scalar(item)}")
    return lines


def emit_yaml(doc: dict) -> str:
    header = ("# GENERATED by tools/formalization_yaml.py — do not hand-edit.\n"
              "# Mechanical fields: regenerate with `--write`. Editorial fields:\n"
              "# edit tools/formalization_meta.toml, then regenerate.\n"
              "# Per-statement informal→Lean map: docs/coverage.md + benchmarks/.\n")
    return header + "\n".join(_emit(doc)) + "\n"


# --- data assembly ------------------------------------------------------------

DOMAIN_SOURCE = "Saporito, Stochastic Processes"


def _load_meta(root: str) -> dict:
    path = os.path.join(root, "tools", "formalization_meta.toml")
    if tomllib is None or not os.path.isfile(path):
        return {}
    with open(path, "rb") as f:
        return tomllib.load(f)


def _theorems(root: str):
    """Yield (benchmark_file_basename, theorem_dict) for every benchmark entry."""
    for path in sorted(glob.glob(os.path.join(root, "benchmarks", "*.json"))):
        try:
            data = json.load(open(path))
        except (OSError, ValueError):
            continue
        thms = data.get("theorems", data) if isinstance(data, dict) else data
        base = os.path.basename(path)
        for t in thms:
            yield base, t


def build_doc(root: str) -> dict:
    meta = _load_meta(root)
    by_file: dict[str, dict] = {}
    totals = {"full": 0, "library_wrapper": 0, "reduced_core": 0, "placeholder": 0}
    n = 0
    # provenance: entries the autoform pipeline scouted carry
    # metadata.provenance.source == "leanstral-autoform" (+ the issue it closed).
    # Counting them here keeps the automation disclosure MECHANICAL — it can never
    # drift from a hand-set "0" once machine-scouted proofs start merging.
    autoform_count = 0
    autoform_issues: list = []
    # provenance: entries re-formalized (translated + cited) from an external
    # formalization carry metadata.provenance.source == "afp-actuarial-mathematics".
    # Counting them keeps the "these are translations, not independent derivations"
    # disclosure MECHANICAL — it cannot drift from a hand-set number.
    afp_count = 0
    afp_issues: list = []
    autoform_models: set = set()
    autoform_drafters: set = set()
    autoform_drafter_counts: dict = {}
    for base, t in _theorems(root):
        n += 1
        md = t.get("metadata") or {}
        status = md.get("formalization_status", "full")
        totals[status] = totals.get(status, 0) + 1
        prov = md.get("provenance") or {}
        if prov.get("source") == "leanstral-autoform":
            autoform_count += 1
            if prov.get("issue") is not None:
                autoform_issues.append(prov["issue"])
            # The disclosure names the models the CORPUS actually records, rather
            # than a pipeline hardcoded here. The pipeline changes (magistral was the
            # statement drafter until 2026-07-29, then left entirely); a hardcoded
            # sentence stays accurate only until the next entry lands, and this file
            # is the public AI-disclosure artifact — the one place a stale claim is
            # least acceptable. Entries keep their own historical attribution.
            # the prover is fixed by `source == leanstral-autoform`; the drafter
            # model is whatever the entry recorded, and is simply absent once the
            # convention went drafter-agnostic
            autoform_models.add(str(prov.get("model") or "labs-leanstral-1-5"))
            sm = prov.get("statement_model")
            if sm and sm != "autoform":
                autoform_models.add(str(sm))
            src = str(prov.get("statement_source") or "autoform").replace("-autoform", "")
            if src != "autoform":
                autoform_drafters.add(src)
            # per-drafter tallies: naming a drafter beside the TOTAL credits it with
            # entries it never touched once the pipeline has had more than one.
            autoform_drafter_counts[src] = autoform_drafter_counts.get(src, 0) + 1
        elif prov.get("source") == "afp-actuarial-mathematics":
            afp_count += 1
            if prov.get("issue") is not None:
                afp_issues.append(prov["issue"])
        d = by_file.setdefault(base, {"n": 0, "full": 0, "library_wrapper": 0,
                                      "reduced_core": 0, "placeholder": 0,
                                      "domain": t.get("domain", ""),
                                      "alignment_sources": set()})
        d["n"] += 1
        d[status] = d.get(status, 0) + 1
        source = md.get("alignment_source")
        if isinstance(source, str) and source.strip():
            d["alignment_sources"].add(source.strip())

    ready = totals["full"] + totals["library_wrapper"]
    # Two-stage is the shape; WHO fills each stage is read off the corpus, so this
    # sentence cannot outlive the pipeline it describes. Entries drafted before a model
    # left keep naming it — that is their honest history — and a drafter the entries do
    # not name is not invented here (the current drafter is deliberately unattributed).
    # When one drafter accounts for every entry, name it plainly. Once the corpus holds
    # entries from more than one drafter — or from a drafter and the later
    # drafter-agnostic convention — each gets its own count, because "N proofs, statement
    # specified by X" reads as a claim about all N.
    named = sorted(autoform_drafters)
    if len(named) == 1 and autoform_drafter_counts.get(named[0]) == autoform_count:
        drafter = named[0].title()
    elif named:
        parts = [f"{d.title()} ({autoform_drafter_counts.get(d, 0)})" for d in named]
        unattributed = autoform_drafter_counts.get("autoform", 0)
        if unattributed:
            parts.append(f"an unnamed drafter ({unattributed})")
        drafter = " and ".join(parts) if len(parts) == 2 else ", ".join(parts)
    else:
        drafter = "an unnamed drafter"
    autoform_note = (f"{autoform_count} autoformalized proof(s) merged "
                     f"(two-stage: statement specified by {drafter}, formalization + proof by "
                     "Leanstral)")
    # `drafter` carries per-entry counts, which belong in the tally sentence above. The
    # pipeline description below is about SHAPE, so it names the drafters without counts
    # and takes a plural verb once there is more than one.
    shape_names = [d.title() for d in named] + (
        ["an unnamed drafter"] if autoform_drafter_counts.get("autoform") else [])
    if not shape_names:
        shape_names = ["an unnamed drafter"]
    drafter_shape = (" and ".join(shape_names) if len(shape_names) == 2
                     else ", ".join(shape_names))
    specifies = "specifies" if len(shape_names) == 1 else "specify"
    if autoform_issues:
        issues = ", ".join("#" + str(i) for i in sorted(set(autoform_issues)))
        autoform_note += f" (closing {issues})"
    afp_note = (f"{afp_count} proof(s) authored in our own design, with Yosuke Ito's AFP "
                f"'Actuarial Mathematics' (Survival_Model, BSD) consulted as a source and cited")
    if afp_issues:
        issues = ", ".join("#" + str(i) for i in sorted(set(afp_issues)))
        afp_note += f" (issues {issues})"

    proj = meta.get("project", {})
    # v0.4 / Palomar mandate `description` (the public registry abstract) and
    # `responsible_maintainers`. Both are editorial — the side-car owns them.
    project = {
        "name": proj.get("name", "formal-mathfin"),
        "description": " ".join(proj.get("description", "").split()),
        "authors": proj.get("authors", []),
        "license": proj.get("license", "Apache-2.0"),
        "responsible_maintainers": proj.get("responsible_maintainers", []),
    }

    cls = meta.get("classification", {})
    classification = {
        "arxiv": cls.get("arxiv", []),
        "msc2020": cls.get("msc2020", []),
    }

    # v0.4 source contract: every source carries a `relationship` drawn from
    # {formalizes, adapts, independently-proves, background, other}, and result
    # origin is derived from `sources` rather than a top-level provenance block.
    # Optional fields are omitted rather than emitted empty.
    sources = []
    for src in meta.get("sources", []):
        row = {
            "title": src.get("title", ""),
            "authors": src.get("authors", []),
            "id": src.get("id", ""),
            "type": src.get("type", ""),
            "relationship": src.get("relationship", "background"),
            "license": src.get("license", "unknown"),
            "author_endorsement": src.get("author_endorsement", "not-contacted"),
        }
        if src.get("location"):
            row["location"] = src["location"]
        if src.get("note"):
            row["note"] = src["note"]
        sources.append(row)

    main_results = []
    for m in meta.get("main_results", []):
        row = {"declaration": m.get("declaration", ""), "file": m.get("file", ""),
               "sorry_count": 0, "axioms": AXIOMS}
        if m.get("literature"):
            row["literature_dependencies"] = [{"statement": m["literature"],
                                               "source": m.get("source", "")}]
        main_results.append(row)

    alignment_statements = []
    for base in sorted(by_file):
        d = by_file[base]
        alignment_statements.append({
            "source": ("; ".join(sorted(d["alignment_sources"]))
                       or f"{d['domain']} ({DOMAIN_SOURCE})"),
            "lean": f"{d['n']} statements",
            "module": f"benchmarks/{base}",
            "status": (f"full {d['full']} · wrapper {d['library_wrapper']} · "
                       f"reduced {d['reduced_core']} · placeholder {d['placeholder']}"),
            "note": "per-statement map in docs/coverage.md",
        })

    review = meta.get("review", {})
    doc = {
        "version": "v0.4",
        "project": project,
        "classification": classification,
        "sources": sources,
        "status": {
            "scope": (f"{n} theorems across continuous-time stochastic processes and "
                      f"mathematical finance, built on Mathlib + BrownianMotion; "
                      f"{ready} delivery-ready (full + library-wrapper)."),
            "sorry_count": 0,
            "sorry_in_definitions": 0,
            "axioms": AXIOMS,
            "main_results": main_results,
        },
        "automation": {
            "methods": [
                {
                    "method": "copilot",
                    "models": ["Claude Code (authoring assistant)"],
                    "framework": "Lean 4 + Mathlib + BrownianMotion; VS Code / lean-repl daemon",
                    "tool_setup": ("interactive human authoring: lake build; AxiomAudit + "
                                   "verification-ledger + values-review gates"),
                    "cost": {
                        "wall_time": "continuous over 2026-05 to 2026-08",
                        "spend_usd": "subscription-based",
                        "hardware": "local machine",
                    },
                    "prompting_notes": "author edits MathFin/<Section>/*.lean directly",
                },
                {
                    "method": "agent",
                    "models": sorted(autoform_models) or ["labs-leanstral-1-5"],
                    "framework": "formal-foundry: probe / vibe <-> lean-lsp-mcp",
                    "tool_setup": (f"token-paced GitHub Actions pipeline; {drafter_shape} "
                                   f"{specifies} the "
                                   "statement, Leanstral formalizes + proves it. A cheap autop "
                                   "tactic-probe may scout-close a goal Leanstral missed; those "
                                   "open as DRAFT PRs (labeled scout-proof, attributed to the "
                                   "tactic, refactored before merge, never silently merged). On a "
                                   "Leanstral pass it opens a ready-for-review PR on formal-mathfin "
                                   "that a human reviews (8-lens values panel) and merges"),
                    "cost": {
                        "wall_time": "token-paced CI runs",
                        "spend_usd": "0 (Mistral Labs beta)",
                        "hardware": "GitHub Actions runners",
                    },
                    "prompting_notes": autoform_note,
                },
                {
                    "method": "manual",
                    "models": [],
                    "framework": ("Lean 4 + Mathlib, this library's conventions; an Isabelle/HOL "
                                  "AFP entry consulted as a source for the classical result set"),
                    "tool_setup": ("provenance.source == afp-actuarial-mathematics; per-file "
                                   "citation header; cited with the author's permission"),
                    "cost": {
                        "wall_time": "not tracked",
                        "spend_usd": "0",
                        "hardware": "local machine",
                    },
                    "prompting_notes": afp_note,
                },
            ],
            "spend_usd": "0 (Mistral Labs beta)",
            "notes": ("scout, not author: the pipeline opens the PR; a human reviews and merges, "
                      "so no machine proof enters the library unreviewed"),
        },
        "fidelity": {
            "divergences": (
                f"{totals['reduced_core']} reduced-core (a faithful but reduced formal core "
                f"of the informal statement) and {totals['library_wrapper']} library-wrappers "
                f"(a thin restatement consuming a Mathlib/BrownianMotion lemma); "
                f"{totals['placeholder']} placeholders. The reduced-core entries are the honest "
                f"divergences — each is itemised in docs/coverage.md."),
        },
        "review": {
            "status": ("continuous — an 8-lens values-review panel runs at each proof-content "
                       "change (docs/values-review.md); cadence machine-enforced by "
                       "test_values_review_is_current"),
            "reviewers": review.get("reviewers", []),
            "notes": "the review is an upgrade engine (ranked backlog), not a pass/fail gate",
        },
        "alignment": {
            "namespace": "MathFin",
            "statements": alignment_statements,
        },
        "acknowledgements": meta.get("acknowledgements", ""),
    }
    return doc


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true", help="regenerate formalization.yaml")
    ap.add_argument("--check", action="store_true", help="exit 1 if stale")
    ap.add_argument("--root", default=ROOT)
    args = ap.parse_args()

    text = emit_yaml(build_doc(args.root))
    out = os.path.join(args.root, "formalization.yaml")

    if args.write:
        with open(out, "w", encoding="utf-8") as f:
            f.write(text)
        print(f"wrote {out}")
        return 0
    if args.check:
        current = open(out, encoding="utf-8").read() if os.path.isfile(out) else ""
        if current != text:
            print("formalization.yaml is STALE — run "
                  "`python3 -m tools.formalization_yaml --write`", file=sys.stderr)
            return 1
        print("formalization.yaml is fresh")
        return 0
    sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
