import SharpWasserstein.RoughFiniteAction
#print axioms SharpWasserstein.RoughEulerianTransport.actionUnitScale
#print axioms SharpWasserstein.RoughEulerianTransport.actionUnitScale_pos
#print axioms SharpWasserstein.RoughEulerianTransport.actionUnitScale_le_one
#print axioms SharpWasserstein.RoughEulerianTransport.actionUnitScale_tendsto
#print axioms SharpWasserstein.RoughEulerianTransport.actionTimeScale
#print axioms SharpWasserstein.RoughEulerianTransport.actionTimeScale_pos
#print axioms SharpWasserstein.RoughEulerianTransport.actionTimeScale_le
#print axioms SharpWasserstein.RoughEulerianTransport.actionTimeScale_tendsto
#print axioms SharpWasserstein.RoughEulerianTransport.actionTimeScale_interior
#print axioms SharpWasserstein.RoughEulerianTransport.euclideanQuadraticLaw
#print axioms SharpWasserstein.RoughEulerianTransport.compressedMeasure_quadratic
#print axioms SharpWasserstein.RoughEulerianTransport.compressedMeasure_configuration
#print axioms SharpWasserstein.RoughEulerianTransport.compressedMeasure_wassersteinSq_tendsto
#print axioms SharpWasserstein.RoughEulerianTransport.spaceTimeQuadraticLaw
#print axioms SharpWasserstein.RoughEulerianTransport.compressed_wassersteinSq_le_uniform_action
#print axioms SharpWasserstein.RoughEulerianTransport.wassersteinSq_le_uniform_action
#print axioms SharpWasserstein.RoughEulerianTransport.uniform_finite_action_transport
