import SharpWasserstein.WeightedPeriodicFourierAverage
import SharpWasserstein.WeightedPeriodicFourierSmoothing
import SharpWasserstein.WeightedPeriodicFourierApproximation
import SharpWasserstein.WeightedPeriodicFourierClosure
#print axioms SharpWasserstein.WeightedPeriodicFourier.continuous_integrable_cube_banach
#print axioms SharpWasserstein.WeightedPeriodicFourier.translatedLift
#print axioms SharpWasserstein.WeightedPeriodicFourier.translatedLift_periodic
#print axioms SharpWasserstein.WeightedPeriodicFourier.translatedLift_zero
#print axioms SharpWasserstein.WeightedPeriodicFourier.translatedLift_integral_apply
#print axioms SharpWasserstein.WeightedPeriodicFourier.testAverage_uniform_tendsto
#print axioms SharpWasserstein.WeightedPeriodicFourier.testAverage_add
#print axioms SharpWasserstein.WeightedPeriodicFourier.testAverage_smul
#print axioms SharpWasserstein.WeightedPeriodicFourier.testAverage_sub
#print axioms SharpWasserstein.WeightedPeriodicFourier.testAverage_cosine
#print axioms SharpWasserstein.WeightedPeriodicFourier.testAverage_sine
#print axioms SharpWasserstein.WeightedPeriodicFourier.testAverage_frequencySpace
#print axioms SharpWasserstein.WeightedPeriodicFourier.continuous_memLp_two_cube
#print axioms SharpWasserstein.WeightedPeriodicFourier.testAverage_eq_shifted
#print axioms SharpWasserstein.WeightedPeriodicFourier.testAverage_abs_le_L2
#print axioms SharpWasserstein.WeightedPeriodicFourier.smoothedPolynomial_uniform_tendsto
#print axioms SharpWasserstein.WeightedPeriodicFourier.smoothedPolynomial_partial_uniform_tendsto
#print axioms SharpWasserstein.WeightedPeriodicFourier.testAverage_partial_uniform_tendsto
#print axioms SharpWasserstein.WeightedPeriodicFourier.exists_frequencySpace_uniform_C1
#print axioms SharpWasserstein.WeightedPeriodicFourier.pullback_gradient_component
#print axioms SharpWasserstein.WeightedPeriodicFourier.pullback_gradient_bound
#print axioms SharpWasserstein.WeightedPeriodicFourier.pullback_value_bound
#print axioms SharpWasserstein.WeightedPeriodicFourier.pullback_gradient_sub_bound
#print axioms SharpWasserstein.WeightedPeriodicFourier.periodic_gradient_memLp
#print axioms SharpWasserstein.WeightedPeriodicFourier.gradientVector
#print axioms SharpWasserstein.WeightedPeriodicFourier.gradientVector_ae
#print axioms SharpWasserstein.WeightedPeriodicFourier.periodicGradientMap
#print axioms SharpWasserstein.WeightedPeriodicFourier.frequencyTestInclusion
#print axioms SharpWasserstein.WeightedPeriodicFourier.trialGradient
#print axioms SharpWasserstein.WeightedPeriodicFourier.trialSpace
#print axioms SharpWasserstein.WeightedPeriodicFourier.periodicSpace
#print axioms SharpWasserstein.WeightedPeriodicFourier.trialSpace_le_periodicSpace
#print axioms SharpWasserstein.WeightedPeriodicFourier.gradientVector_norm_sub_le
#print axioms SharpWasserstein.WeightedPeriodicFourier.gradientVector_mem_periodicSpace
#print axioms SharpWasserstein.WeightedPeriodicFourier.periodicSpace_eq_smoothGradientClosure
