import SharpWasserstein.PeriodicSourceConvolutionSmooth
#print axioms SharpWasserstein.PeriodicSourceConvolution.joint_fderiv_eq
#print axioms SharpWasserstein.PeriodicSourceConvolution.joint_fderiv_bounded
#print axioms SharpWasserstein.PeriodicSourceConvolution.joint_euclideanKernelTest_bounded
#print axioms SharpWasserstein.PeriodicSourceConvolution.joint_coordinateDerivative_bounded
#print axioms SharpWasserstein.PeriodicSourceConvolution.joint_generator_bounded
#print axioms SharpWasserstein.PeriodicSourceConvolution.joint_euclideanGenerator_bounded
#print axioms SharpWasserstein.PeriodicSourceConvolution.action_smooth_param
#print axioms SharpWasserstein.PeriodicSourceConvolution.convolvedSource_smooth
#print axioms SharpWasserstein.PeriodicSourceConvolution.convolvedSource_periodic
#print axioms SharpWasserstein.PeriodicSourceConvolution.convolvedSource_allDerivativesBounded
#print axioms SharpWasserstein.PeriodicSourceConvolution.convolvedSourceTimeDerivative
#print axioms SharpWasserstein.PeriodicSourceConvolution.convolvedSourceTimeDerivative_smooth
#print axioms SharpWasserstein.PeriodicSourceConvolution.convolvedSourceTimeDerivative_periodic
#print axioms SharpWasserstein.PeriodicSourceConvolution.convolvedSourceTimeDerivative_allDerivativesBounded
#print axioms SharpWasserstein.PeriodicSourceConvolution.convolvedSourceDerivativeBCF_apply
