import SharpWasserstein.WeightedPeriodicMarginal
#print axioms SharpWasserstein.WeightedPeriodicMarginal.liftTest
#print axioms SharpWasserstein.WeightedPeriodicMarginal.tangentLift_gradientVector
#print axioms SharpWasserstein.WeightedPeriodicMarginal.tangentLift_periodic_mem
#print axioms SharpWasserstein.WeightedPeriodicMarginal.periodicLift
#print axioms SharpWasserstein.WeightedPeriodicMarginal.periodicLift_ae
#print axioms SharpWasserstein.WeightedPeriodicMarginal.representative_closed_pairing
#print axioms SharpWasserstein.WeightedPeriodicMarginal.source_liftTest
#print axioms SharpWasserstein.WeightedPeriodicMarginal.marginal_representative_pairing
#print axioms SharpWasserstein.WeightedPeriodicMarginal.marginal_energy_increment
#print axioms SharpWasserstein.WeightedPeriodicMarginal.marginal_energy_increment_integral
#print axioms SharpWasserstein.WeightedPeriodicMarginal.marginal_energy_le
