import SharpWasserstein.RegularizedTrialConvergence
import SharpWasserstein.RegularizedTrialConvergencePeriodic
import SharpWasserstein.RegularizedTrialConvergenceFourier
import SharpWasserstein.RegularizedTrialConvergenceTime
import SharpWasserstein.RegularizedTrialConvergenceSequence
import SharpWasserstein.RegularizedTrialConvergencePhysical
import SharpWasserstein.RegularizedTrialConvergencePhysicalTime

#print axioms SharpWasserstein.RegularizedTrialConvergence.synthesis
#print axioms SharpWasserstein.RegularizedTrialConvergence.synthesis_apply
#print axioms SharpWasserstein.RegularizedTrialConvergence.coefficients
#print axioms SharpWasserstein.RegularizedTrialConvergence.synthesis_coefficients
#print axioms SharpWasserstein.RegularizedTrialConvergence.coefficients_norm_sq
#print axioms SharpWasserstein.RegularizedTrialConvergence.exists_finite_recovery
#print axioms SharpWasserstein.RegularizedTrialConvergence.energy_tendsto
#print axioms SharpWasserstein.RegularizedTrialConvergence.energy_error_bounds
#print axioms SharpWasserstein.RegularizedTrialConvergencePeriodic.atomTest
#print axioms SharpWasserstein.RegularizedTrialConvergencePeriodic.frequency_image_mem_span
#print axioms SharpWasserstein.RegularizedTrialConvergencePeriodic.iSup_trialRange_eq_atomSpan
#print axioms SharpWasserstein.RegularizedTrialConvergencePeriodic.closed_trialRange_eq_atomClosure
#print axioms SharpWasserstein.RegularizedTrialConvergenceFourier.Atom
#print axioms SharpWasserstein.RegularizedTrialConvergenceFourier.atomPotential
#print axioms SharpWasserstein.RegularizedTrialConvergenceFourier.atomPotential_smooth
#print axioms SharpWasserstein.RegularizedTrialConvergenceFourier.atomPotential_gradient_bound
#print axioms SharpWasserstein.RegularizedTrialConvergenceFourier.atomVector
#print axioms SharpWasserstein.RegularizedTrialConvergenceFourier.frequency_gradient_mem_atomSpan
#print axioms SharpWasserstein.RegularizedTrialConvergenceFourier.periodic_mem_atomClosure
#print axioms SharpWasserstein.RegularizedTrialConvergenceFourier.trial
#print axioms SharpWasserstein.RegularizedTrialConvergenceFourier.trial_eq_synthesis
#print axioms SharpWasserstein.RegularizedTrialConvergenceFourier.energy_tendsto
#print axioms SharpWasserstein.RegularizedTrialConvergence.energy_aestronglyMeasurable
#print axioms SharpWasserstein.RegularizedTrialConvergence.integral_energy_error_tendsto
#print axioms SharpWasserstein.RegularizedTrialConvergence.integral_norm_energy_error_tendsto
#print axioms SharpWasserstein.RegularizedTrialConvergence.integral_norm_energy_error_tendsto_of_bound
#print axioms SharpWasserstein.RegularizedTrialConvergence.exhaustion
#print axioms SharpWasserstein.RegularizedTrialConvergence.mem_exhaustion
#print axioms SharpWasserstein.RegularizedTrialConvergence.exhaustion_monotone
#print axioms SharpWasserstein.RegularizedTrialConvergence.eventually_mem_exhaustion
#print axioms SharpWasserstein.RegularizedTrialConvergence.penalty
#print axioms SharpWasserstein.RegularizedTrialConvergence.penalty_pos
#print axioms SharpWasserstein.RegularizedTrialConvergence.penalty_tendsto
#print axioms SharpWasserstein.RegularizedTrialConvergence.canonical_energy_tendsto
#print axioms SharpWasserstein.RegularizedTrialConvergencePhysical.atomVector
#print axioms SharpWasserstein.RegularizedTrialConvergencePhysical.periodic_mem_atomClosure
#print axioms SharpWasserstein.RegularizedTrialConvergencePhysical.trial
#print axioms SharpWasserstein.RegularizedTrialConvergencePhysical.trial_eq_synthesis
#print axioms SharpWasserstein.RegularizedTrialConvergencePhysical.energy_tendsto
#print axioms SharpWasserstein.RegularizedTrialConvergencePhysical.integral_norm_energy_error_tendsto_of_bound
#print axioms SharpWasserstein.RegularizedTrialConvergencePhysical.canonical_integral_norm_energy_error_tendsto
