import SharpWasserstein.PeriodicMarginalCoefficientEvolutionConsistency
import SharpWasserstein.PeriodicMarginalCoefficientEvolutionEnergy
#print axioms SharpWasserstein.PeriodicMarginalCoefficientEvolution.prefix_comp_observation
#print axioms SharpWasserstein.PeriodicMarginalCoefficientEvolution.prefix_observation
#print axioms SharpWasserstein.PeriodicMarginalCoefficientEvolution.marginalLaw_observation
#print axioms SharpWasserstein.PeriodicMarginalCoefficientEvolution.marginalDistribution_observedSource
#print axioms SharpWasserstein.PeriodicMarginalCoefficientEvolution.observedSource_eq_imageSource
#print axioms SharpWasserstein.PeriodicMarginalCoefficientEvolution.prefixSource_eq_imageSource
#print axioms SharpWasserstein.PeriodicMarginalCoefficientEvolution.periodic_marginalEnergy_observedSource
#print axioms SharpWasserstein.PeriodicMarginalCoefficientEvolution.periodicPrefixField
#print axioms SharpWasserstein.PeriodicMarginalCoefficientEvolution.observed_trialEnergy_eq_prefix
#print axioms SharpWasserstein.PeriodicMarginalCoefficientEvolution.brownian_marginal_optimizedEnergy_hasDerivWithinAt
#print axioms SharpWasserstein.PeriodicMarginalCoefficientEvolution.brownian_periodic_sourceVector_eq
#print axioms SharpWasserstein.PeriodicMarginalCoefficientEvolution.brownian_periodic_trialEnergy_hasDerivWithinAt
