import SharpWasserstein.DerivativeCompositionThird
import SharpWasserstein.GaussianEulerBackwardThird
import SharpWasserstein.BoundedDerivativeComposition
import SharpWasserstein.GaussianEulerBackwardSmooth
#print axioms SharpWasserstein.lipschitz_clm_comp_bounded
#print axioms SharpWasserstein.compL_lipschitz_one
#print axioms SharpWasserstein.compL_flip_lipschitz_one
#print axioms SharpWasserstein.lipschitz_secondFDeriv_comp
#print axioms SharpWasserstein.BackwardEuler.secondFDeriv_mean
#print axioms SharpWasserstein.BackwardEuler.lipschitz_secondFDeriv_mean
#print axioms SharpWasserstein.BackwardEuler.contDiff_three_step
#print axioms SharpWasserstein.BackwardEuler.lipschitz_secondFDeriv_step
#print axioms SharpWasserstein.BackwardEuler.lipschitz_secondFDeriv_backward
#print axioms SharpWasserstein.BackwardEuler.contDiff_three_backward
#print axioms SharpWasserstein.BackwardEuler.thirdBound_le
#print axioms SharpWasserstein.BackwardEuler.thirdBound_le_exp
#print axioms SharpWasserstein.NoiseAverage.allDerivativesBounded_const
#print axioms SharpWasserstein.NoiseAverage.AllDerivativesBounded.add
#print axioms SharpWasserstein.NoiseAverage.AllDerivativesBounded.const_smul
#print axioms SharpWasserstein.NoiseAverage.AllDerivativesBounded.comp_of_fderiv
#print axioms SharpWasserstein.BackwardEuler.allDerivativesBounded_fderiv_mean
#print axioms SharpWasserstein.BackwardEuler.smooth_step
#print axioms SharpWasserstein.BackwardEuler.smooth_backward
