import SharpWasserstein.BrownianSourceInitialFlux
import SharpWasserstein.InitialCurrentBrownianSource
import SharpWasserstein.BrownianSourceCoordinatePairing
#print axioms SharpWasserstein.PropagatedSourceEquation.Brownian.sourceAt_zero_pairing
#print axioms SharpWasserstein.PropagatedSourceEquation.Brownian.sourceAt_zero_of_divergence
#print axioms SharpWasserstein.PropagatedSourceEquation.Brownian.lawAt_zero
#print axioms SharpWasserstein.InitialSourcePermutation.euclidean_initialCurrent_covariant
#print axioms SharpWasserstein.InitialSourcePermutation.current_sourceAt_zero
#print axioms SharpWasserstein.PropagatedSourceEquation.Brownian.sourceAt_configuration_pairing
