import SharpWasserstein.BrownianGrid
import SharpWasserstein.BrownianFlowWeak
#check MeasurableSpace.pi
#check MeasurableSpace.comap_comp
#check MeasurableSpace.comap_iSup
#check ProbabilityTheory.IndepFun.comp
#check ProbabilityTheory.IndepFun.hasLaw_prod
#check ProbabilityTheory.HasLaw.prod
#check ProbabilityTheory.IndepFun.map_prod_eq_prod_map_map
#check ProbabilityTheory.HasLaw.comp
#check ProbabilityTheory.IndepFun.comp_measurable
#check ProbabilityTheory.Indep.mono
#check ProbabilityTheory.HasLaw.congr
#check MeasureTheory.MeasurePreserving.prod
#check MeasureTheory.MeasurePreserving.pi
#check MeasureTheory.measurePreserving_arrowProdEquivProdArrow
#check ProbabilityTheory.isBrownianReal_brownian
#check ProbabilityTheory.IsPreBrownianReal.hasLaw_gaussianLimit
#print SharpWasserstein.FiniteAdditiveTrajectory
