import SharpWasserstein.GaussianBridgeBrownian
import SharpWasserstein.TestGenerator
#print axioms SharpWasserstein.configurationFlatten_symm_add
#print axioms SharpWasserstein.configurationFlatten_symm_sub
#print axioms SharpWasserstein.configurationFlatten_symm_smul
#print axioms SharpWasserstein.flattenedDrift_shifted
#print axioms SharpWasserstein.GaussianBridge.initialX
#print axioms SharpWasserstein.GaussianBridge.initialY
#print axioms SharpWasserstein.GaussianBridge.measurable_initialX
#print axioms SharpWasserstein.GaussianBridge.measurable_initialY
#print axioms SharpWasserstein.GaussianBridge.endpointObservation
#print axioms SharpWasserstein.GaussianBridge.endpointObservation_measurable
#print axioms SharpWasserstein.GaussianBridge.current_initialX
#print axioms SharpWasserstein.GaussianBridge.mean_ordinary_eq
#print axioms SharpWasserstein.GaussianBridge.mean_shifted_eq
#print axioms SharpWasserstein.GaussianBridge.observation_eq
#print axioms SharpWasserstein.GaussianBridge.brownianEndpointX
#print axioms SharpWasserstein.GaussianBridge.brownianEndpointY
#print axioms SharpWasserstein.GaussianBridge.ordinaryLaw_endpoint_eq
#print axioms SharpWasserstein.GaussianBridge.shiftedLaw_endpoint_eq
#print axioms SharpWasserstein.CompactGenerator.coordinate_test
#print axioms SharpWasserstein.CompactGenerator.laplacian_test
#print axioms SharpWasserstein.CompactGenerator.generator_continuous
#print axioms SharpWasserstein.CompactGenerator.generator_compact
#print axioms SharpWasserstein.CompactGenerator.integrable
#print axioms SharpWasserstein.CompactGenerator.expectation_continuous
