import SharpWasserstein.FiniteGradientTrialLaplacian
import SharpWasserstein.BoundedHessianIntegrability
import SharpWasserstein.FiniteGradientTrialDiffusion
import SharpWasserstein.FiniteCoefficientMatrix
import SharpWasserstein.FiniteCoefficientEnergy
import SharpWasserstein.WeightedEnergyDerivativeWithin
import SharpWasserstein.FiniteCoefficientEnergyDerivative
import SharpWasserstein.FiniteCoefficientBrownianEnergy
#print axioms SharpWasserstein.FiniteGradientTrial.laplacian_const_mul
#print axioms SharpWasserstein.FiniteGradientTrial.diagonalCoefficients
#print axioms SharpWasserstein.FiniteGradientTrial.inner_diagonalCoefficients
#print axioms SharpWasserstein.FiniteGradientTrial.potential_laplacian
#print axioms SharpWasserstein.FiniteGradientTrial.solution_laplacian_pairing
#print axioms SharpWasserstein.BochnerIdentity.hessian_entry_continuous
#print axioms SharpWasserstein.BochnerIdentity.hessian_entry_norm_bound
#print axioms SharpWasserstein.BochnerIdentity.hessian_square_integrable
#print axioms SharpWasserstein.FiniteGradientTrial.potential_allDerivativesBounded
#print axioms SharpWasserstein.FiniteGradientTrial.potential_gradient_memLp
#print axioms SharpWasserstein.FiniteGradientTrial.solution_diffusion_identity
#print axioms SharpWasserstein.FiniteCoefficientMatrix.matrixOperator
#print axioms SharpWasserstein.FiniteCoefficientMatrix.matrixOperator_apply
#print axioms SharpWasserstein.FiniteCoefficientMatrix.matrixOperator_single
#print axioms SharpWasserstein.FiniteCoefficientMatrix.matrixOperator_entries
#print axioms SharpWasserstein.FiniteCoefficientMatrix.matrixOperator_hasDerivAt
#print axioms SharpWasserstein.FiniteCoefficientMatrix.matrixOperator_hasDerivWithinAt
#print axioms SharpWasserstein.FiniteCoefficientMatrix.coefficientVector
#print axioms SharpWasserstein.FiniteCoefficientMatrix.coefficientVector_apply
#print axioms SharpWasserstein.FiniteCoefficientMatrix.coefficientVector_hasDerivAt
#print axioms SharpWasserstein.FiniteCoefficientMatrix.coefficientVector_hasDerivWithinAt
#print axioms SharpWasserstein.FiniteCoefficientEnergy.gramMatrix
#print axioms SharpWasserstein.FiniteCoefficientEnergy.sourceVector
#print axioms SharpWasserstein.FiniteCoefficientEnergy.optimizedEnergy
#print axioms SharpWasserstein.FiniteCoefficientEnergy.gramMatrix_eq
#print axioms SharpWasserstein.FiniteCoefficientEnergy.sourceVector_eq
#print axioms SharpWasserstein.FiniteCoefficientEnergy.gramMatrix_isUnit
#print axioms SharpWasserstein.FiniteCoefficientEnergy.gramMatrix_symmetric
#print axioms SharpWasserstein.FiniteCoefficientEnergy.optimizedEnergy_eq
#print axioms SharpWasserstein.WeightedEnergyDerivative.hasDerivWithinAt_inverseSolution
#print axioms SharpWasserstein.WeightedEnergyDerivative.hasDerivWithinAt_optimizedEnergy
#print axioms SharpWasserstein.FiniteCoefficientEnergy.gramMatrix_hasDerivWithinAt
#print axioms SharpWasserstein.FiniteCoefficientEnergy.optimizedEnergy_hasDerivWithinAt
#print axioms SharpWasserstein.FiniteCoefficientEnergy.brownian_optimizedEnergy_hasDerivWithinAt
