import SharpWasserstein.RegularizedTrialEnergy
import SharpWasserstein.FiniteGradientTrial
import SharpWasserstein.FiniteGradientTrialPairing
#print axioms SharpWasserstein.RegularizedTrialEnergy.gram
#print axioms SharpWasserstein.RegularizedTrialEnergy.gram_inner
#print axioms SharpWasserstein.RegularizedTrialEnergy.gram_symmetric
#print axioms SharpWasserstein.RegularizedTrialEnergy.gram_coercive
#print axioms SharpWasserstein.RegularizedTrialEnergy.gram_isUnit
#print axioms SharpWasserstein.RegularizedTrialEnergy.solution
#print axioms SharpWasserstein.RegularizedTrialEnergy.solution_equation
#print axioms SharpWasserstein.RegularizedTrialEnergy.energy
#print axioms SharpWasserstein.RegularizedTrialEnergy.solution_tested
#print axioms SharpWasserstein.RegularizedTrialEnergy.energy_eq_penalized_norm
#print axioms SharpWasserstein.RegularizedTrialEnergy.energy_nonneg
#print axioms SharpWasserstein.RegularizedTrialEnergy.energy_gap
#print axioms SharpWasserstein.RegularizedTrialEnergy.energy_le
#print axioms SharpWasserstein.RegularizedTrialEnergy.energy_gap_le_trial
#print axioms SharpWasserstein.FiniteGradientTrial.atomGradient
#print axioms SharpWasserstein.FiniteGradientTrial.atomGradient_ae
#print axioms SharpWasserstein.FiniteGradientTrial.gradientMap
#print axioms SharpWasserstein.FiniteGradientTrial.gradientMap_apply
#print axioms SharpWasserstein.FiniteGradientTrial.potential
#print axioms SharpWasserstein.FiniteGradientTrial.potential_smooth
#print axioms SharpWasserstein.FiniteGradientTrial.potential_gradient
#print axioms SharpWasserstein.FiniteGradientTrial.gradientMap_ae
#print axioms SharpWasserstein.FiniteGradientTrial.gradientMap_norm_sq
#print axioms SharpWasserstein.FiniteGradientTrial.gradientMap_single
#print axioms SharpWasserstein.FiniteGradientTrial.gradientMap_pairing
#print axioms SharpWasserstein.FiniteGradientTrial.gradientMap_source_pairing
#print axioms SharpWasserstein.FiniteGradientTrial.adjoint_source_coefficient
#print axioms SharpWasserstein.FiniteGradientTrial.gram_coefficient
#print axioms SharpWasserstein.FiniteGradientTrial.gram_matrix_entry
