import SharpWasserstein.WeightedConvolutionSmooth
import SharpWasserstein.PeriodicFluxSmooth
import SharpWasserstein.PeriodicFluxEuclidean
import SharpWasserstein.PeriodicFluxOptimizer
import SharpWasserstein.PeriodicConvolvedOptimizer
#print axioms SharpWasserstein.WeightedConvolution.operatorAverage
#print axioms SharpWasserstein.WeightedConvolution.operatorIntegrand_measurable
#print axioms SharpWasserstein.WeightedConvolution.operatorIntegrand_integrable
#print axioms SharpWasserstein.WeightedConvolution.continuous_operatorAverage
#print axioms SharpWasserstein.WeightedConvolution.hasFDerivAt_operatorAverage
#print axioms SharpWasserstein.WeightedConvolution.fderiv_operatorAverage
#print axioms SharpWasserstein.WeightedConvolution.contDiff_nat_operatorAverage
#print axioms SharpWasserstein.WeightedConvolution.contDiff_infty_operatorAverage
#print axioms SharpWasserstein.PeriodicConvolution.flux_smooth_of_integrable
#print axioms SharpWasserstein.PeriodicConvolution.hasFDerivAt_flux_of_integrable
#print axioms SharpWasserstein.PeriodicConvolution.fderiv_flux_of_integrable
#print axioms SharpWasserstein.PeriodicConvolution.allDerivativesBounded_flux_of_integrable
#print axioms SharpWasserstein.PeriodicConvolution.fluxSource
#print axioms SharpWasserstein.PeriodicConvolution.fluxSource_smooth_of_integrable
#print axioms SharpWasserstein.PeriodicConvolution.fluxSource_periodic
#print axioms SharpWasserstein.PeriodicConvolution.integral_fluxSource_mul
#print axioms SharpWasserstein.PeriodicConvolution.integral_fluxSource_eq_zero
#print axioms SharpWasserstein.PeriodicConvolution.allDerivativesBounded_fluxSource_of_integrable
#print axioms SharpWasserstein.PeriodicConvolution.fluxVelocity_smooth_of_integrable
#print axioms SharpWasserstein.PeriodicConvolution.euclidean_flux_eq
#print axioms SharpWasserstein.PeriodicConvolution.euclideanGradient
#print axioms SharpWasserstein.PeriodicConvolution.euclideanGradient_apply
#print axioms SharpWasserstein.PeriodicConvolution.euclideanGradient_periodic
#print axioms SharpWasserstein.PeriodicConvolution.euclideanGradient_continuous
#print axioms SharpWasserstein.PeriodicConvolution.integral_fluxSource_euclidean
#print axioms SharpWasserstein.PeriodicConvolution.integral_fluxSource_convolved_test
#print axioms SharpWasserstein.PeriodicConvolution.integral_fluxSource_tendsto
#print axioms SharpWasserstein.PeriodicConvolution.integral_euclidean_fluxVelocity_sq_le
#print axioms SharpWasserstein.PeriodicFluxOptimizer.functional
#print axioms SharpWasserstein.PeriodicFluxOptimizer.functional_apply
#print axioms SharpWasserstein.PeriodicFluxOptimizer.integrable_fluxAction
#print axioms SharpWasserstein.PeriodicFluxOptimizer.weighted_young
#print axioms SharpWasserstein.PeriodicFluxOptimizer.optimizer_energy_le_fluxAction
#print axioms SharpWasserstein.PeriodicConvolution.densityBCF
#print axioms SharpWasserstein.PeriodicConvolution.densityBCF_lower
#print axioms SharpWasserstein.PeriodicConvolution.convolvedFlux_memLp
#print axioms SharpWasserstein.PeriodicConvolution.convolvedFluxLp
#print axioms SharpWasserstein.PeriodicConvolution.convolvedFluxLp_ae
#print axioms SharpWasserstein.PeriodicConvolution.convolvedFunctional
#print axioms SharpWasserstein.PeriodicConvolution.convolvedFunctional_gradient
#print axioms SharpWasserstein.PeriodicConvolution.convolvedFunctional_trialGradient
#print axioms SharpWasserstein.PeriodicConvolution.convolved_optimizer_energy_le
