import SharpWasserstein.EntropyChainRule

#print axioms SharpWasserstein.measurable_kernel_klDiv
#print axioms SharpWasserstein.rnDeriv_compProd_same_base_eq_kernel
#print axioms SharpWasserstein.lintegral_kernel_klDiv_eq_compProd
#print axioms SharpWasserstein.ae_kernel_klDiv_ne_top
#print axioms SharpWasserstein.integrable_kernel_klDiv_toReal
#print axioms SharpWasserstein.integral_kernel_klDiv_toReal_eq_compProd
#print axioms SharpWasserstein.conditional_joint_klDiv_ne_top
#print axioms SharpWasserstein.integral_kernel_klDiv_eq_entropy_increment
#print axioms SharpWasserstein.integrated_kernel_norm_difference_sq_le_entropy_increment
