import SharpWasserstein.EntropyNarrow

#print axioms SharpWasserstein.entropyLogClip_measurable
#print axioms SharpWasserstein.entropyLogClip_abs_le
#print axioms SharpWasserstein.entropyLogClip_fenchel_nonneg
#print axioms SharpWasserstein.entropyLogClip_fenchel_tendsto
#print axioms SharpWasserstein.absolutelyContinuous_of_bounded_entropy_tests
#print axioms SharpWasserstein.klDiv_le_of_bounded_entropy_tests
#print axioms SharpWasserstein.bounded_entropy_test_le_klDiv
#print axioms SharpWasserstein.entropy_abs_exp_sub_le
#print axioms SharpWasserstein.entropy_clip_error_le
#print axioms SharpWasserstein.klDiv_le_of_continuous_entropy_tests
#print axioms SharpWasserstein.klDiv_le_liminf_of_narrow
#print axioms SharpWasserstein.klDiv_le_of_narrow_entropy_bound
