import SharpWasserstein.ExternalInteractionEnergyLimit
import SharpWasserstein.ExternalInteractionEnergyLimitWeighted
import SharpWasserstein.ExternalInteractionEnergyLimitPotentials
import SharpWasserstein.ExternalInteractionEnergyLimitEstimate
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.galerkinResidual
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.optimizerResidual
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.galerkinResidual_tendsto
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.galerkinResidual_weighted_square_tendsto
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.galerkinResidual_energy_increment_tendsto
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.galerkinResidual_ae
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.literal_galerkin_fluctuation_energy_tendsto
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.weightedCube
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.weightedCube_le
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.memLp_weightedCube
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.integrable_weightedCube
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.integral_weightedCube
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.continuous_integrable_cubePoint
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.continuous_memLp_cubePoint
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.continuous_frobenius_hessian
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.weighted_external_le
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.gradientVector_field_ae
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.marginalPotential
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.marginalPotential_smooth
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.marginalPotential_gradient_ae
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.marginalPotential_prefix_gradient_ae
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.galerkinResidual_potential_ae
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.potential_fluctuation_energy_tendsto
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.potential_marginal_energy_tendsto
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.integral_densityBCF_prefix
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.externalGalerkinTerm
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.hessianGalerkinTerm
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.hessianGalerkinTerm_eq_marginal
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.externalGalerkin_absorbed_le
#print axioms SharpWasserstein.ExternalInteractionEnergyLimit.externalGalerkin_absorbed_eventually_le
