import SharpWasserstein.FiniteCoefficientBrownianGenerator
import SharpWasserstein.FiniteTrialEnergyEstimate
import SharpWasserstein.FiniteTrialEnergyInequality
#print axioms SharpWasserstein.FiniteCoefficientEnergy.brownian_optimizedEnergy_generator
#print axioms SharpWasserstein.FiniteGradientTrial.integrable_memLp_pairing
#print axioms SharpWasserstein.FiniteGradientTrial.integral_drift_residual_le
#print axioms SharpWasserstein.FiniteGradientTrial.solution_residual_integral
#print axioms SharpWasserstein.FiniteGradientTrial.solution_residual_integral_le
#print axioms SharpWasserstein.FiniteGradientTrial.jacobian_integral_le
#print axioms SharpWasserstein.FiniteGradientTrial.solution_generator_le
