import SharpWasserstein.FiniteTrialDriftResidual
import SharpWasserstein.PropagatedFluxSmoothPairing
import SharpWasserstein.FiniteGeneratorCalculus
import SharpWasserstein.FiniteGeneratorPairing
import SharpWasserstein.FiniteGeneratorBounds
import SharpWasserstein.BrownianSourceSmoothPairing
import SharpWasserstein.FiniteTrialEnergyIdentity
#print axioms SharpWasserstein.FiniteTrialDriftResidual.gradient_drift
#print axioms SharpWasserstein.FiniteTrialDriftResidual.gradient_drift_norm_sq_le
#print axioms SharpWasserstein.FiniteTrialDriftResidual.drift_residual_young
#print axioms SharpWasserstein.PropagatedFlux.representative_pairing
#print axioms SharpWasserstein.PropagatedFlux.representative_bounded_smooth_pairing
#print axioms SharpWasserstein.FiniteGeneratorCalculus.generator
#print axioms SharpWasserstein.FiniteGeneratorCalculus.generator_potential
#print axioms SharpWasserstein.FiniteGeneratorCalculus.gradientSquare_potential
#print axioms SharpWasserstein.FiniteGeneratorCalculus.generator_gradientSquare_potential
#print axioms SharpWasserstein.FiniteGeneratorCalculus.matrixGenerator_quadratic
#print axioms SharpWasserstein.FiniteGeneratorCalculus.sourceGenerator_pairing
#print axioms SharpWasserstein.FiniteGeneratorCalculus.directionDeriv_allDerivativesBounded
#print axioms SharpWasserstein.FiniteGeneratorCalculus.laplacian_allDerivativesBounded
#print axioms SharpWasserstein.FiniteGeneratorCalculus.generator_eq
#print axioms SharpWasserstein.FiniteGeneratorCalculus.generator_smooth
#print axioms SharpWasserstein.FiniteGeneratorCalculus.generator_allDerivativesBounded
#print axioms SharpWasserstein.FiniteGeneratorCalculus.euclideanGenerator_eq
#print axioms SharpWasserstein.FiniteGeneratorCalculus.generator_integrable
#print axioms SharpWasserstein.PropagatedSourceEquation.Brownian.action_eq_representative_pairing
#print axioms SharpWasserstein.FiniteGradientTrial.integrable_smooth_gradient_pairing
#print axioms SharpWasserstein.FiniteGradientTrial.gradient_fun_add
#print axioms SharpWasserstein.FiniteGradientTrial.solution_generator_identity
