import SharpWasserstein.GaussianBridgeLimit

#print axioms SharpWasserstein.GaussianBridge.sum_real_range
#print axioms SharpWasserstein.GaussianBridge.sum_real_range_sq
#print axioms SharpWasserstein.GaussianBridge.gridCost_eq
#print axioms SharpWasserstein.GaussianBridge.gridCost_tendsto
#print axioms SharpWasserstein.klDiv_le_of_narrow_converging_cost
#print axioms SharpWasserstein.GaussianBridge.gridStep_ne_zero
#print axioms SharpWasserstein.GaussianBridge.gridStep_terminal
#print axioms SharpWasserstein.GaussianBridge.limit_observation_entropy_le
