import SharpWasserstein.InternalSourceProfile

#print axioms SharpWasserstein.integrable_exp_square_standardGaussian
#print axioms SharpWasserstein.integral_exp_square_standardGaussian
#print axioms SharpWasserstein.integral_exp_square_le_of_subGaussian
#print axioms SharpWasserstein.centeredProductSum_subGaussian
#print axioms SharpWasserstein.centeredProductSum_abs_le
#print axioms SharpWasserstein.shifted_centeredProductSum_exp_square_le
#print axioms SharpWasserstein.internalScalarCurrent_exp_square_le
#print axioms SharpWasserstein.internalScalarCurrent_sq_le_entropy
#print axioms SharpWasserstein.internal_source_energy_le_entropy
#print axioms SharpWasserstein.internalCurrentSquare_exp_le
#print axioms SharpWasserstein.internal_source_marginal_energy_le_profile
#print axioms SharpWasserstein.subGaussianSquare_gaussian_density_identity
#print axioms SharpWasserstein.internalSource_convex_exp_mean_le
