import SharpWasserstein.PeriodicMarginalLift
import SharpWasserstein.PeriodicMarginalEnergy
import SharpWasserstein.ExternalInteractionEnergy
import SharpWasserstein.ExternalInteractionEnergyCancellation
#print axioms SharpWasserstein.PeriodicMarginalLift.prefixCoords_measurePreserving
#print axioms SharpWasserstein.PeriodicMarginalLift.coordinate_measurePreserving
#print axioms SharpWasserstein.PeriodicMarginalLift.coordinateSymm_measurePreserving
#print axioms SharpWasserstein.PeriodicMarginalLift.prefix_measurePreserving
#print axioms SharpWasserstein.PeriodicMarginalLift.cubePoint_prefix_map
#print axioms SharpWasserstein.PeriodicMarginalLift.liftLinear
#print axioms SharpWasserstein.PeriodicMarginalLift.liftLinear_ae
#print axioms SharpWasserstein.PeriodicMarginalLift.liftLinear_norm
#print axioms SharpWasserstein.PeriodicMarginalLift.lift
#print axioms SharpWasserstein.PeriodicMarginalLift.lift_gradientClosure_mem
#print axioms SharpWasserstein.PeriodicMarginalLift.gradientLiftLinear
#print axioms SharpWasserstein.PeriodicMarginalLift.gradientLift
#print axioms SharpWasserstein.PeriodicMarginalLift.prefixLinear
#print axioms SharpWasserstein.PeriodicMarginalLift.prefix_smooth
#print axioms SharpWasserstein.PeriodicMarginalLift.prefix_periodic
#print axioms SharpWasserstein.PeriodicMarginalLift.gradientLift_gradientVector
#print axioms SharpWasserstein.PeriodicMarginalLift.gradientLift_periodic_mem
#print axioms SharpWasserstein.PeriodicMarginalLift.periodicLift
#print axioms SharpWasserstein.PeriodicMarginalEnergy.integral_densityBCF
#print axioms SharpWasserstein.PeriodicMarginalEnergy.densityPairing_lift
#print axioms SharpWasserstein.PeriodicMarginalEnergy.marginalFunctional
#print axioms SharpWasserstein.PeriodicMarginalEnergy.densityBCF_positive_lower
#print axioms SharpWasserstein.PeriodicMarginalEnergy.optimizer_residual_orthogonal
#print axioms SharpWasserstein.PeriodicMarginalEnergy.optimizer_energy_increment
#print axioms SharpWasserstein.PeriodicMarginalEnergy.optimizer_energy_increment_integral
#print axioms SharpWasserstein.ExternalInteraction.gradientConstant
#print axioms SharpWasserstein.ExternalInteraction.gradientConstant_nonneg
#print axioms SharpWasserstein.ExternalInteraction.interaction_gradient_memLp
#print axioms SharpWasserstein.ExternalInteraction.integral_interaction_gradient_sq_le
#print axioms SharpWasserstein.ExternalInteraction.integral_pairing_abs_le
#print axioms SharpWasserstein.ExternalInteraction.integral_pairing_sq_le
#print axioms SharpWasserstein.ExternalInteraction.liftedGradient
#print axioms SharpWasserstein.ExternalInteraction.fluctuation
#print axioms SharpWasserstein.ExternalInteraction.fluctuation_memLp
#print axioms SharpWasserstein.ExternalInteraction.fluctuation_pairing_sq_le
#print axioms SharpWasserstein.ExternalInteraction.young_of_sq_le
#print axioms SharpWasserstein.ExternalInteraction.fluctuation_pairing_young
#print axioms SharpWasserstein.ExternalInteraction.diagonalEnergy_abs_le
#print axioms SharpWasserstein.ExternalInteraction.diagonalEnergy_integrable
#print axioms SharpWasserstein.ExternalInteraction.integral_diagonalEnergy_le
#print axioms SharpWasserstein.ExternalInteraction.lifted_energy_transport_integrable
#print axioms SharpWasserstein.ExternalInteraction.integral_external_decomposition
#print axioms SharpWasserstein.ExternalInteraction.integral_external_le
