import SharpWasserstein.PeriodicDriftGradientBound
import SharpWasserstein.PeriodicDriftResidual
import SharpWasserstein.PeriodicJacobianLimit
import SharpWasserstein.PeriodicCoefficientBounds
import SharpWasserstein.PeriodicParabolicEnergy
import SharpWasserstein.FlowInitialDerivativeLinear
import SharpWasserstein.FlowInitialDerivativeRemainder
import SharpWasserstein.FlowInitialDerivative
import SharpWasserstein.FlowInitialDerivativeGlobal
import SharpWasserstein.FlowInitialDerivativeSmooth
import SharpWasserstein.PeriodicConvolutionWeak
#print axioms SharpWasserstein.PeriodicDriftGradientBound.coordinatePartial_sum
#print axioms SharpWasserstein.PeriodicDriftGradientBound.coordinatePartial_drift
#print axioms SharpWasserstein.PeriodicDriftGradientBound.gradientSquare_drift_le
#print axioms SharpWasserstein.PeriodicDriftGradientBound.gradientVector_norm_sq
#print axioms SharpWasserstein.PeriodicDriftGradientBound.gradientVector_drift_norm_sq_le
#print axioms SharpWasserstein.PeriodicDriftGradientBound.potential_drift_gradient_uniform_bound
#print axioms SharpWasserstein.PeriodicDriftResidual.periodic_drift
#print axioms SharpWasserstein.PeriodicDriftResidual.weightedOperator_gradientVector_inner
#print axioms SharpWasserstein.PeriodicDriftResidual.residual
#print axioms SharpWasserstein.PeriodicDriftResidual.residual_tendsto_zero
#print axioms SharpWasserstein.PeriodicDriftResidual.finite_drift_pairing_integral
#print axioms SharpWasserstein.PeriodicDriftResidual.finite_drift_pairing
#print axioms SharpWasserstein.PeriodicJacobianLimit.matrix_memLp
#print axioms SharpWasserstein.PeriodicJacobianLimit.matrixMultiply
#print axioms SharpWasserstein.PeriodicJacobianLimit.matrixMultiply_ae
#print axioms SharpWasserstein.PeriodicJacobianLimit.matrixLinear
#print axioms SharpWasserstein.PeriodicJacobianLimit.matrixMultiply_norm_le
#print axioms SharpWasserstein.PeriodicJacobianLimit.matrixOperator
#print axioms SharpWasserstein.PeriodicJacobianLimit.matrixOperator_ae
#print axioms SharpWasserstein.PeriodicJacobianLimit.inner_matrixOperator
#print axioms SharpWasserstein.PeriodicJacobianLimit.integral_quadratic_tendsto
#print axioms SharpWasserstein.PeriodicJacobianLimit.integrable_matrix_inner
#print axioms SharpWasserstein.PeriodicJacobianLimit.fderiv_vectorPullback
#print axioms SharpWasserstein.PeriodicJacobianLimit.exists_jacobian_bound
#print axioms SharpWasserstein.PeriodicJacobianLimit.jacobianField
#print axioms SharpWasserstein.PeriodicJacobianLimit.jacobianField_apply
#print axioms SharpWasserstein.PeriodicJacobianLimit.jacobianCoefficient
#print axioms SharpWasserstein.PeriodicJacobianLimit.jacobianCoefficient_apply
#print axioms SharpWasserstein.PeriodicJacobianLimit.inner_jacobianCoefficient
#print axioms SharpWasserstein.PeriodicJacobianLimit.integrable_jacobian_inner
#print axioms SharpWasserstein.PeriodicJacobianLimit.inner_jacobian_gradientVector
#print axioms SharpWasserstein.PeriodicJacobianLimit.inner_jacobian_vector
#print axioms SharpWasserstein.PeriodicJacobianLimit.potential_jacobianForm_tendsto
#print axioms SharpWasserstein.PeriodicJacobianLimit.potential_jacobianForm_cube_tendsto
#print axioms SharpWasserstein.PeriodicJacobianLimit.jacobian_integral_le
#print axioms SharpWasserstein.PeriodicJacobianLimit.optimizer_jacobian_integral_le
#print axioms SharpWasserstein.PeriodicCoefficientBounds.vector_periodic
#print axioms SharpWasserstein.PeriodicCoefficientBounds.exists_coordinate_bound
#print axioms SharpWasserstein.PeriodicCoefficientBounds.coordinateDerivativeField
#print axioms SharpWasserstein.PeriodicCoefficientBounds.continuous_coordinateDerivativeField
#print axioms SharpWasserstein.PeriodicCoefficientBounds.periodic_coordinateDerivativeField
#print axioms SharpWasserstein.PeriodicCoefficientBounds.exists_first_partial_bound
#print axioms SharpWasserstein.PeriodicCoefficientBounds.exists_drift_bounds
#print axioms SharpWasserstein.PeriodicCoefficientBounds.periodic_laplacian
#print axioms SharpWasserstein.PeriodicCoefficientBounds.continuous_laplacian
#print axioms SharpWasserstein.PeriodicCoefficientBounds.exists_laplacian_norm_bound
#print axioms SharpWasserstein.PeriodicCoefficientBounds.exists_laplacian_upper_bound
#print axioms SharpWasserstein.PeriodicCoefficientBounds.residual_tendsto_zero_of_smooth
#print axioms SharpWasserstein.PeriodicParabolicEnergy.finiteDerivativePairing_eq
#print axioms SharpWasserstein.PeriodicParabolicEnergy.derivativePairing_le_jacobian
#print axioms SharpWasserstein.PeriodicParabolicEnergy.derivativePairing_le
#print axioms SharpWasserstein.PeriodicParabolicEnergy.deriv_energy_le
#print axioms SharpWasserstein.FlowInitialDerivative.LinearVariation
#print axioms SharpWasserstein.FlowInitialDerivative.exists_linearVariation_short
#print axioms SharpWasserstein.FlowInitialDerivative.LinearVariation.derivative_right
#print axioms SharpWasserstein.FlowInitialDerivative.LinearVariation.norm_le_exp
#print axioms SharpWasserstein.FlowInitialDerivative.taylor_error_le_lipschitz_fderiv
#print axioms SharpWasserstein.FlowInitialDerivative.trajectory_linearization_error
#print axioms SharpWasserstein.FlowInitialDerivative.hasFDerivAt_of_quadratic_error
#print axioms SharpWasserstein.FlowInitialDerivative.autonomousFlow
#print axioms SharpWasserstein.FlowInitialDerivative.exists_flow_jacobian_short
#print axioms SharpWasserstein.FlowInitialDerivative.flow_fderiv_norm_le_exp_short
#print axioms SharpWasserstein.FlowInitialDerivative.autonomousFlow_endpoint_differentiable_multiple
#print axioms SharpWasserstein.FlowInitialDerivative.autonomousFlow_endpoint_differentiable
#print axioms SharpWasserstein.FlowInitialDerivative.autonomousFlow_hasFDerivAt_and_norm
#print axioms SharpWasserstein.FlowInitialDerivative.autonomousFlow_hasFDerivAt_and_norm_of_boundedSmooth
#print axioms SharpWasserstein.FlowInitialDerivative.boundedFlow_hasFDerivAt_and_norm_of_boundedSmooth
#print axioms SharpWasserstein.WeakEvolution.bounded_generatorExpectation_uniformContinuousOn
#print axioms SharpWasserstein.WeakEvolution.bounded_generatorExpectation_continuousOn
#print axioms SharpWasserstein.WeakEvolution.hasDerivWithinAt_bounded_configuration
#print axioms SharpWasserstein.PeriodicConvolution.flattenCLM
#print axioms SharpWasserstein.PeriodicConvolution.flattenCLM_apply
#print axioms SharpWasserstein.PeriodicConvolution.kernelTest
#print axioms SharpWasserstein.PeriodicConvolution.kernelTest_smooth
#print axioms SharpWasserstein.PeriodicConvolution.kernelTest_derivatives_bounded
#print axioms SharpWasserstein.PeriodicConvolution.density_flatten_eq_integral
#print axioms SharpWasserstein.PeriodicConvolution.evolutionDensity
#print axioms SharpWasserstein.PeriodicConvolution.evolutionDensity_equation
#print axioms SharpWasserstein.PeriodicConvolution.evolutionDensity_generator_continuousOn
#print axioms SharpWasserstein.PeriodicConvolution.evolutionDensity_hasDerivWithinAt
#print axioms SharpWasserstein.PeriodicConvolution.evolutionDensity_hasDerivAt
#print axioms SharpWasserstein.PeriodicConvolution.evolutionDensity_joint_continuous_nonnegExtension
