import SharpWasserstein.CompressionPeriodicTests
import SharpWasserstein.PeriodicEnergyExhaustion
import SharpWasserstein.KernelPeriodMultiples
#print axioms SharpWasserstein.CompressionPeriodicTests.compression_scaled
#print axioms SharpWasserstein.CompressionPeriodicTests.compression_scaled_tendsto
#print axioms SharpWasserstein.CompressionPeriodicTests.compression_fderiv
#print axioms SharpWasserstein.CompressionPeriodicTests.compression_scaled_fderiv_tendsto
#print axioms SharpWasserstein.CompressionPeriodicTests.compressed_gradient
#print axioms SharpWasserstein.CompressionPeriodicTests.compressed_gradient_bound
#print axioms SharpWasserstein.CompressionPeriodicTests.compressed_gradient_tendsto
#print axioms SharpWasserstein.CompressionPeriodicTests.compression_coordinates
#print axioms SharpWasserstein.CompressionPeriodicTests.compressed_periodic
#print axioms SharpWasserstein.PeriodicEnergyExhaustion.smooth_periodic_objective_le
#print axioms SharpWasserstein.PeriodicEnergyExhaustion.full_energy_le_of_periodic_multiples
#print axioms SharpWasserstein.KernelPeriodMultiples.first
#print axioms SharpWasserstein.KernelPeriodMultiples.second
