import SharpWasserstein.SinePeriodizationDerivative
import SharpWasserstein.PeriodicParticleDerivative
#print axioms SharpWasserstein.SinePeriodization.scalar_hasDerivAt
#print axioms SharpWasserstein.SinePeriodization.coordinateProjection
#print axioms SharpWasserstein.SinePeriodization.coordinateDerivative
#print axioms SharpWasserstein.SinePeriodization.coordinateDerivative_apply
#print axioms SharpWasserstein.SinePeriodization.coordinateProjection_sum
#print axioms SharpWasserstein.SinePeriodization.coordinates_hasFDerivAt
#print axioms SharpWasserstein.SinePeriodization.fderiv_coordinates
#print axioms SharpWasserstein.SinePeriodization.coordinateDerivative_tendsto
#print axioms SharpWasserstein.SinePeriodization.coordinates_tendsto
#print axioms SharpWasserstein.SinePeriodization.coordinates_moving_tendsto
#print axioms SharpWasserstein.SinePeriodization.fderiv_kernel
#print axioms SharpWasserstein.SinePeriodization.fderiv_kernel_moving_tendsto
#print axioms SharpWasserstein.PeriodicParticle.pairProjection
#print axioms SharpWasserstein.PeriodicParticle.driftDerivative
#print axioms SharpWasserstein.PeriodicParticle.particleDrift_hasFDerivAt
#print axioms SharpWasserstein.PeriodicParticle.fderiv_particleDrift
#print axioms SharpWasserstein.PeriodicParticle.driftDerivative_moving_tendsto
#print axioms SharpWasserstein.PeriodicParticle.fderiv_particleDrift_moving_tendsto
#print axioms SharpWasserstein.PeriodicParticle.fderiv_linearConjugate
#print axioms SharpWasserstein.PeriodicParticle.euclidean_fderiv_particleDrift_moving_tendsto
