import SharpWasserstein.PeriodicDriftCommutator
import SharpWasserstein.PeriodicKernelConcentration
#print axioms SharpWasserstein.WeightedIntegralSquare.weighted_scalar_sq_le
#print axioms SharpWasserstein.WeightedIntegralSquare.weighted_norm_integral_sq_le
#print axioms SharpWasserstein.PeriodicConvolution.flux
#print axioms SharpWasserstein.PeriodicConvolution.commutator
#print axioms SharpWasserstein.PeriodicConvolution.kernel_smul_integrable
#print axioms SharpWasserstein.PeriodicConvolution.commutator_eq_integral
#print axioms SharpWasserstein.PeriodicConvolution.commutator_action_le
#print axioms SharpWasserstein.PeriodicPositiveKernel.peak
#print axioms SharpWasserstein.PeriodicPositiveKernel.peak_continuous
#print axioms SharpWasserstein.PeriodicPositiveKernel.peak_periodic
#print axioms SharpWasserstein.PeriodicPositiveKernel.cos_eq_one_iff_circle_zero
#print axioms SharpWasserstein.PeriodicPositiveKernel.peak_lt_at_zero
#print axioms SharpWasserstein.PeriodicPositiveKernel.peak_pow
#print axioms SharpWasserstein.PeriodicPositiveKernel.peak_pow_integral
#print axioms SharpWasserstein.PeriodicPositiveKernel.kernel_eq_peak_normalized
#print axioms SharpWasserstein.PeriodicPositiveKernel.integral_kernel_tendsto
