import SharpWasserstein.PhysicalFourierTrialExternal
import SharpWasserstein.PhysicalFourierTrialHierarchy
import SharpWasserstein.InternalDriftFiniteBounds
#print axioms SharpWasserstein.PhysicalFourierTrialExternal.integral_external_trial_le
#print axioms SharpWasserstein.PhysicalFourierTrialHierarchy.finite_hierarchy_le
#print axioms SharpWasserstein.PhysicalFourierTrialHierarchy.finite_terminal_le
#print axioms SharpWasserstein.ExternalInteractionPeriodic.internalDrift_eq_scaled
#print axioms SharpWasserstein.ExternalInteractionPeriodic.internalDrift_allDerivativesBounded
#print axioms SharpWasserstein.ExternalInteractionPeriodic.internalDrift_lipschitz
#print axioms SharpWasserstein.ExternalInteractionPeriodic.internalDrift_fderiv_bound
