import SharpWasserstein.VolterraEnergyLimit
import SharpWasserstein.RegularizedTrialMarginal
import SharpWasserstein.PhysicalFourierTrialMarginal
import SharpWasserstein.PhysicalFourierTrialBounds
import SharpWasserstein.PhysicalGeneratorPeriodicity
#print axioms SharpWasserstein.VolterraEnergyLimit.integrating_factor_bound
#print axioms SharpWasserstein.VolterraEnergyLimit.weighted_error_tendsto
#print axioms SharpWasserstein.VolterraEnergyLimit.limit_integrating_factor_bound
#print axioms SharpWasserstein.RegularizedTrialEnergy.lifted_energy_gap
#print axioms SharpWasserstein.RegularizedTrialEnergy.lifted_energy_gap_le
#print axioms SharpWasserstein.PhysicalFourierTrialMarginal.trial_mem_periodic
#print axioms SharpWasserstein.PhysicalFourierTrialMarginal.trial_representative_pairing
#print axioms SharpWasserstein.PhysicalFourierTrialMarginal.trial_fluctuation_norm_sq
#print axioms SharpWasserstein.PhysicalFourierTrialMarginal.trial_fluctuation_integral
#print axioms SharpWasserstein.WeightedPeriodicFourierPhysical.physicalPotential_allDerivativesBounded
#print axioms SharpWasserstein.WeightedPeriodicFourierPhysical.physicalAtom_laplacian
#print axioms SharpWasserstein.WeightedPeriodicFourierPhysical.physicalAtom_eigenvalue_nonneg
#print axioms SharpWasserstein.PhysicalGeneratorPeriodicity.directionDeriv_periodic
#print axioms SharpWasserstein.PhysicalGeneratorPeriodicity.laplacian_periodic
#print axioms SharpWasserstein.PhysicalGeneratorPeriodicity.generator_periodic
