import SharpWasserstein.SwitchSourceBrownianPairing
import SharpWasserstein.PrescribedSwitchBrownianSource
import SharpWasserstein.PrescribedSwitchBrownianLaw
import SharpWasserstein.SwitchCurveNarrow
import SharpWasserstein.PrescribedSwitchContinuity
#print axioms SharpWasserstein.SwitchSourceDerivative.sourcePairing_eq_brownianSourceAt
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedCurrent_memLp
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedBrownianSource
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedBrownianSource_pairing
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedBrownianSource_lawAt
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedBrownianSource_finite
#print axioms SharpWasserstein.SwitchCurve.jointEndpoint
#print axioms SharpWasserstein.SwitchCurve.jointEndpoint_continuous
#print axioms SharpWasserstein.SwitchCurve.law_eq_jointEndpoint
#print axioms SharpWasserstein.SwitchCurve.probabilityCurve
#print axioms SharpWasserstein.SwitchCurve.probabilityCurve_continuous
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedEuclideanCurve
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedEuclideanCurve_continuous
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedBrownianSource_clamped_pairing
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedBrownianSource_continuous
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedEuclideanCurve_sub_eq_integral
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribed_compactDistributionContinuity
