import SharpWasserstein.PeriodicConvolutionWeakBCF
import SharpWasserstein.PeriodicFluxContraction
import SharpWasserstein.PeriodicFluxPairing
import SharpWasserstein.FlowJacobianContinuityLocal
import SharpWasserstein.FlowJacobianContinuityGlobal
import SharpWasserstein.FlowJacobianContinuitySmooth
#print axioms SharpWasserstein.PeriodicConvolution.kernelTest_eq_translate
#print axioms SharpWasserstein.PeriodicConvolution.lipschitz_translate
#print axioms SharpWasserstein.PeriodicConvolution.kernelTest_uniform_lipschitz
#print axioms SharpWasserstein.PeriodicConvolution.evolutionDensity_uniform_generator
#print axioms SharpWasserstein.PeriodicConvolution.evolutionDensity_uniform_remainder
#print axioms SharpWasserstein.PeriodicConvolution.evolutionDensity_generator_continuous_space
#print axioms SharpWasserstein.PeriodicConvolution.evolutionDensity_generator_bounded
#print axioms SharpWasserstein.PeriodicConvolution.evolutionDensityBCF
#print axioms SharpWasserstein.PeriodicConvolution.evolutionDensityBCF_apply
#print axioms SharpWasserstein.PeriodicConvolution.evolutionGeneratorBCF
#print axioms SharpWasserstein.PeriodicConvolution.evolutionGeneratorBCF_apply
#print axioms SharpWasserstein.PeriodicConvolution.evolutionDensityBCF_hasDerivWithinAt
#print axioms SharpWasserstein.PeriodicConvolution.evolutionDensityBCF_hasDerivAt
#print axioms SharpWasserstein.PeriodicConvolution.evolutionGeneratorBCF_uniformContinuousOn
#print axioms SharpWasserstein.PeriodicConvolution.evolutionGeneratorBCF_continuousOn
#print axioms SharpWasserstein.PeriodicConvolution.evolutionDensityBCF_continuousOn
#print axioms SharpWasserstein.PeriodicConvolution.evolutionDensityBCF_bounds
#print axioms SharpWasserstein.PeriodicConvolution.kernel_smul_integrable_of_integrable
#print axioms SharpWasserstein.PeriodicConvolution.flux_continuous_of_integrable
#print axioms SharpWasserstein.PeriodicConvolution.flux_periodic
#print axioms SharpWasserstein.PeriodicConvolution.kernel_mul_integrable_of_integrable
#print axioms SharpWasserstein.PeriodicConvolution.flux_action_le_of_integrable
#print axioms SharpWasserstein.PeriodicConvolution.kernel_normsq_joint_integrable
#print axioms SharpWasserstein.PeriodicConvolution.integral_flux_action_le
#print axioms SharpWasserstein.PeriodicConvolution.fluxVelocity
#print axioms SharpWasserstein.PeriodicConvolution.fluxVelocity_continuous
#print axioms SharpWasserstein.PeriodicConvolution.fluxVelocity_periodic
#print axioms SharpWasserstein.PeriodicConvolution.fluxVelocity_sq_integrable
#print axioms SharpWasserstein.PeriodicConvolution.fluxVelocity_memLp
#print axioms SharpWasserstein.PeriodicConvolution.density_smul_fluxVelocity
#print axioms SharpWasserstein.PeriodicConvolution.integral_fluxVelocity_sq_le
#print axioms SharpWasserstein.PeriodicConvolution.flux_pairing_joint_integrable
#print axioms SharpWasserstein.PeriodicConvolution.integral_inner_flux
#print axioms SharpWasserstein.PeriodicConvolution.integral_inner_fluxVelocity
#print axioms SharpWasserstein.PeriodicConvolution.integral_inner_flux_tendsto
#print axioms SharpWasserstein.FlowInitialDerivative.exists_flow_variation_short
#print axioms SharpWasserstein.FlowInitialDerivative.LinearVariation.difference_le
#print axioms SharpWasserstein.FlowInitialDerivative.autonomousFlow_fderiv_lipschitz_short
#print axioms SharpWasserstein.BoundedFlow.restrictPath_continuous
#print axioms SharpWasserstein.BoundedFlow.shiftPath_continuous
#print axioms SharpWasserstein.FlowInitialDerivative.autonomousFlow_fderiv_continuous_multiple
#print axioms SharpWasserstein.FlowInitialDerivative.autonomousFlow_endpoint_fderiv_continuous
#print axioms SharpWasserstein.FlowInitialDerivative.autonomousFlow_fderiv_continuous
#print axioms SharpWasserstein.FlowInitialDerivative.autonomousFlow_fderiv_continuous_of_boundedSmooth
#print axioms SharpWasserstein.FlowInitialDerivative.boundedFlow_fderiv_continuous_of_boundedSmooth
#print axioms SharpWasserstein.FlowInitialDerivative.boundedFlow_fderiv_measurable_of_boundedSmooth
#print axioms SharpWasserstein.FlowInitialDerivative.boundedFlow_fderiv_apply_aestronglyMeasurable
#print axioms SharpWasserstein.FlowInitialDerivative.boundedFlow_fderiv_apply_memLp
#print axioms SharpWasserstein.FlowInitialDerivative.boundedFlow_fderiv_apply_energy_le
