import SharpWasserstein.PropagatedSourcePermutation
import SharpWasserstein.PropagatedSourcePermutationParticle
import SharpWasserstein.WeightedSourceSymmetry
#print axioms SharpWasserstein.PropagatedSourcePermutation.pullTest
#print axioms SharpWasserstein.PropagatedSourcePermutation.pullTest_gradient_pairing
#print axioms SharpWasserstein.PropagatedSourcePermutation.flow_covariant
#print axioms SharpWasserstein.PropagatedSourcePermutation.flow_fderiv_covariant
#print axioms SharpWasserstein.PropagatedSourcePermutation.expectation_covariant
#print axioms SharpWasserstein.PropagatedSourcePermutation.expectation_fderiv_covariant
#print axioms SharpWasserstein.PropagatedSourcePermutation.source_invariant
#print axioms SharpWasserstein.PropagatedSourcePermutation.euclideanPermutation
#print axioms SharpWasserstein.PropagatedSourcePermutation.euclideanPermutation_coordinates
#print axioms SharpWasserstein.PropagatedSourcePermutation.euclideanPermutation_norm
#print axioms SharpWasserstein.PropagatedSourcePermutation.euclideanPermutationIsometry
#print axioms SharpWasserstein.PropagatedSourcePermutation.euclideanPermutation_gradient
#print axioms SharpWasserstein.PropagatedSourcePermutation.particle_equivDrift_covariant
#print axioms SharpWasserstein.PropagatedSourcePermutation.equivPath_permutation
#print axioms SharpWasserstein.PropagatedSourcePermutation.euclideanBrownianPathLaw_permutation
#print axioms SharpWasserstein.PropagatedSourcePermutation.euclideanLaw_permutation
#print axioms SharpWasserstein.PropagatedSourcePermutation.particle_sourceAt_invariant
#print axioms SharpWasserstein.WeightedSourceSymmetry.measurePreserving_isometry
#print axioms SharpWasserstein.WeightedSourceSymmetry.pullVector
#print axioms SharpWasserstein.WeightedSourceSymmetry.pullVector_ae
#print axioms SharpWasserstein.WeightedSourceSymmetry.pullVector_norm
#print axioms SharpWasserstein.WeightedSourceSymmetry.source_invariant_inverse
#print axioms SharpWasserstein.WeightedSourceSymmetry.pullVector_representative_divergence
#print axioms SharpWasserstein.WeightedSourceSymmetry.representative_equivariant
