import SharpWasserstein.BrownianFlowTimeEnergy
import SharpWasserstein.SwitchCurveTimeEnergy
import SharpWasserstein.PrescribedSwitchCommonLabel
import SharpWasserstein.RoughFiniteActionInterface
import SharpWasserstein.PrescribedSwitchLengthFromAction
import SharpWasserstein.MainFiniteActionReduction
#print axioms SharpWasserstein.BrownianFlow.flow_increment_energy_le
#print axioms SharpWasserstein.SwitchCurve.integral_three_terms
#print axioms SharpWasserstein.SwitchCurve.productCost_triangle_sq
#print axioms SharpWasserstein.SwitchCurve.jointTimeCost
#print axioms SharpWasserstein.SwitchCurve.jointEndpoint_cost_le
#print axioms SharpWasserstein.SwitchCurve.jointEndpoint_energy_le
#print axioms SharpWasserstein.SwitchCurve.jointEndpoint_cost_tendsto
#print axioms SharpWasserstein.SwitchCurve.jointEndpoint_marginal_cost_tendsto
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedMarginalCommonLabel
#print axioms SharpWasserstein.RoughEulerianTransport.UniformFiniteActionTransport
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedMetricCurve_length_of_finiteAction
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribed_switch_length_of_finiteAction
#print axioms SharpWasserstein.main_of_uniform_finite_action_transport
