import SharpWasserstein.GeometricEndpointLength
import SharpWasserstein.RoughEulerianIntervalRestriction
import SharpWasserstein.PrescribedSwitchMetricCurve
import SharpWasserstein.PrescribedSwitchMetricIdentification
import SharpWasserstein.PrescribedSwitchIntervalEnergy
#print axioms SharpWasserstein.GeometricEndpointLength.time
#print axioms SharpWasserstein.GeometricEndpointLength.time_pos
#print axioms SharpWasserstein.GeometricEndpointLength.time_le
#print axioms SharpWasserstein.GeometricEndpointLength.time_succ
#print axioms SharpWasserstein.GeometricEndpointLength.sqrt_time_succ
#print axioms SharpWasserstein.GeometricEndpointLength.endpoint_of_geometric_action
#print axioms SharpWasserstein.GeometricEndpointLength.endpoint_of_local_action
#print axioms SharpWasserstein.RoughEulerianTransport.CompactDistributionContinuity.translate
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedMarginalMetricCurve
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedMarginalMetricCurve_continuous
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedMarginalMetricCurve_distance_sq
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedMarginalCurve_eq_metric
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedMarginalCurve_map_configuration
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedMarginalCurve_secondMoment
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedMarginalSource_finite
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedMarginalCurve_energy_le
#print axioms SharpWasserstein.SwitchSourceDerivative.prescribedMarginalCurve_testObjective_le
