import SharpWasserstein.PeriodicFourierTests
import Mathlib.Analysis.Fourier.AddCircleMulti
#check QuotientAddGroup.isOpenQuotientMap_mk
#check QuotientAddGroup.mk_surjective
#check Function.Periodic.add_period
#check MeasureTheory.MeasurePreserving.integral_comp'
#check MeasureTheory.Measure.volume_pi
#check Complex.exp_sum
#check Complex.exp_mul_I
#check Complex.cos_add_sin_mul_I
#check IsOpenQuotientMap.continuous_comp_iff
#check AddCircle.coe_sub
#check AddCircle.coe_eq_zero_iff
#check QuotientAddGroup.mk_sub
#check Function.Surjective.hasRightInverse
#check Function.rightInverse_invFun
#check AddCircle.fourier_coe_apply
#check fourier_coe_apply
#check AddCircle.volume_eq_smul_haarAddCircle
