import SharpWasserstein.EulerianTransportL2
import SharpWasserstein.EulerianTransportLength
import SharpWasserstein.EulerianTransportCompact
import SharpWasserstein.FlowSemigroupDerivative
import SharpWasserstein.FlowSemigroupDerivativePairing
import SharpWasserstein.PropagatedFlux
import SharpWasserstein.PropagatedFluxFlow
import SharpWasserstein.PeriodicConvolutionPDECalculus
import SharpWasserstein.PeriodicConvolutionPDEIntegral
import SharpWasserstein.PeriodicConvolutionPDE
#print axioms SharpWasserstein.EulerianTransport.norm_toLp_sub_sq
#print axioms SharpWasserstein.EulerianTransport.continuous_toLp_of_uniform_bound
#print axioms SharpWasserstein.EulerianTransport.intervalIntegrable_toLp_of_uniform_bound
#print axioms SharpWasserstein.EulerianTransport.euclideanMap
#print axioms SharpWasserstein.EulerianTransport.euclideanMap_apply
#print axioms SharpWasserstein.EulerianTransport.euclideanMap_norm_sq
#print axioms SharpWasserstein.EulerianTransport.solution_norm_le
#print axioms SharpWasserstein.EulerianTransport.solution_memLp
#print axioms SharpWasserstein.EulerianTransport.flowLaw_secondMoment
#print axioms SharpWasserstein.EulerianTransport.velocity
#print axioms SharpWasserstein.EulerianTransport.velocity_joint_continuous
#print axioms SharpWasserstein.EulerianTransport.velocity_norm_le
#print axioms SharpWasserstein.EulerianTransport.velocity_memLp
#print axioms SharpWasserstein.EulerianTransport.velocity_norm_eq_action
#print axioms SharpWasserstein.EulerianTransport.flowLaw_wassersteinSq_le_action
#print axioms SharpWasserstein.EulerianTransport.WeakContinuity.eq_flowLaw
#print axioms SharpWasserstein.EulerianTransport.WeakContinuity.wassersteinSq_le_action
#print axioms SharpWasserstein.EulerianTransport.WeakContinuity.wasserstein_length_le_action
#print axioms SharpWasserstein.EulerianTransport.exists_compact_test_approximation
#print axioms SharpWasserstein.EulerianTransport.CompactWeakContinuity
#print axioms SharpWasserstein.EulerianTransport.CompactWeakContinuity.toWeakContinuity
#print axioms SharpWasserstein.EulerianTransport.CompactWeakContinuity.wassersteinSq_le_action
#print axioms SharpWasserstein.EulerianTransport.CompactWeakContinuity.eq_flowLaw
#print axioms SharpWasserstein.EulerianTransport.CompactWeakContinuity.wasserstein_length_le_action
#print axioms SharpWasserstein.FlowSemigroupDerivative.expectation
#print axioms SharpWasserstein.FlowSemigroupDerivative.initialMap_lipschitz
#print axioms SharpWasserstein.FlowSemigroupDerivative.integrable_observable
#print axioms SharpWasserstein.FlowSemigroupDerivative.differential_continuous
#print axioms SharpWasserstein.FlowSemigroupDerivative.integrable_differential
#print axioms SharpWasserstein.FlowSemigroupDerivative.hasFDerivAt_expectation
#print axioms SharpWasserstein.FlowSemigroupDerivative.fderiv_expectation_apply
#print axioms SharpWasserstein.FlowSemigroupDerivative.expectation_contDiff_one
#print axioms SharpWasserstein.FlowSemigroupDerivative.norm_fderiv_expectation_le
#print axioms SharpWasserstein.FlowSemigroupDerivative.expectation_zero
#print axioms SharpWasserstein.FlowSemigroupDerivative.integrable_differential_pairing
#print axioms SharpWasserstein.FlowSemigroupDerivative.integral_fderiv_expectation_eq
#print axioms SharpWasserstein.PropagatedFlux.mapPreserving
#print axioms SharpWasserstein.PropagatedFlux.pullback
#print axioms SharpWasserstein.PropagatedFlux.tangentFunctional
#print axioms SharpWasserstein.PropagatedFlux.tangentFunctional_norm_le
#print axioms SharpWasserstein.PropagatedFlux.source
#print axioms SharpWasserstein.PropagatedFlux.source_eq_inner
#print axioms SharpWasserstein.PropagatedFlux.source_apply
#print axioms SharpWasserstein.PropagatedFlux.testObjective_le
#print axioms SharpWasserstein.PropagatedFlux.source_finiteEnergy
#print axioms SharpWasserstein.PropagatedFlux.source_energy_le
#print axioms SharpWasserstein.PropagatedFlux.Flow.endpoint
#print axioms SharpWasserstein.PropagatedFlux.Flow.velocity
#print axioms SharpWasserstein.PropagatedFlux.Flow.endpoint_measurable
#print axioms SharpWasserstein.PropagatedFlux.Flow.velocity_memLp
#print axioms SharpWasserstein.PropagatedFlux.Flow.source
#print axioms SharpWasserstein.PropagatedFlux.Flow.source_apply
#print axioms SharpWasserstein.PropagatedFlux.Flow.source_eq_semigroup_pairing
#print axioms SharpWasserstein.PropagatedFlux.Flow.source_finiteEnergy
#print axioms SharpWasserstein.PropagatedFlux.Flow.source_energy_le
#print axioms SharpWasserstein.PropagatedFlux.Flow.distribution
#print axioms SharpWasserstein.PropagatedFlux.Flow.distribution_apply
#print axioms SharpWasserstein.PropagatedFlux.Flow.distribution_finiteEnergy_and_energy_le
#print axioms SharpWasserstein.PropagatedFlux.Flow.distribution_zero
#print axioms SharpWasserstein.PeriodicConvolution.flattenEquiv
#print axioms SharpWasserstein.PeriodicConvolution.flattenEquiv_apply
#print axioms SharpWasserstein.PeriodicConvolution.flattenEquiv_coordinateVector
#print axioms SharpWasserstein.PeriodicConvolution.coordinateDerivative_flatten
#print axioms SharpWasserstein.PeriodicConvolution.laplacian_flatten
#print axioms SharpWasserstein.PeriodicConvolution.coordinatePartial_reflect
#print axioms SharpWasserstein.PeriodicConvolution.laplacian_reflect
#print axioms SharpWasserstein.PeriodicConvolution.generator_kernelTest
#print axioms SharpWasserstein.PeriodicConvolution.flattenEquiv_symm_apply
#print axioms SharpWasserstein.PeriodicConvolution.flattenedDrift
#print axioms SharpWasserstein.PeriodicConvolution.flattenedDrift_continuous
#print axioms SharpWasserstein.PeriodicConvolution.flattenedDrift_at_flatten
#print axioms SharpWasserstein.PeriodicConvolution.flattenedDrift_contDiff
#print axioms SharpWasserstein.PeriodicConvolution.divergence_sub
#print axioms SharpWasserstein.PeriodicConvolution.divergence_commutator
#print axioms SharpWasserstein.PeriodicConvolution.coordinatePartial_average
#print axioms SharpWasserstein.PeriodicConvolution.laplacian_average
#print axioms SharpWasserstein.PeriodicConvolution.laplacian_density
#print axioms SharpWasserstein.PeriodicConvolution.kernelFDeriv_smulRight_integrable
#print axioms SharpWasserstein.PeriodicConvolution.coordinatePartial_flux
#print axioms SharpWasserstein.PeriodicConvolution.fderiv_eq_sum_coordinatePartial
#print axioms SharpWasserstein.PeriodicConvolution.divergence_flux
#print axioms SharpWasserstein.PeriodicConvolution.kernel_drift_integrable
#print axioms SharpWasserstein.PeriodicConvolution.kernel_laplacian_integrable
#print axioms SharpWasserstein.PeriodicConvolution.flattenedDrift_integrable
#print axioms SharpWasserstein.PeriodicConvolution.integral_generator_kernelTest_eq
#print axioms SharpWasserstein.PeriodicConvolution.integral_generator_kernelTest_eq_commutator
#print axioms SharpWasserstein.PeriodicConvolution.evolutionGeneratorBCF_eq_laplacian_sub_divergence
#print axioms SharpWasserstein.PeriodicConvolution.evolutionDensity_hasDerivWithinAt_pde
#print axioms SharpWasserstein.PeriodicConvolution.evolutionDensity_hasDerivAt_pde
#print axioms SharpWasserstein.PeriodicConvolution.evolutionGeneratorBCF_eq_commutator
